/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author ALEJO
 */
public class viewActualizarTicket extends javax.swing.JInternalFrame {

    /**
     * Creates new form viewRegistrarTicket
     */
    public viewActualizarTicket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        combocategoria = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        btnactualizarticket = new javax.swing.JButton();
        btncancelarticket = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 227, 203));
        setBorder(null);
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(970, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(238, 227, 203));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("MS Gothic", 1, 44)); // NOI18N
        jLabel3.setText("ACTUALIZACIÓN DE TICKETS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 580, 50));

        jLabel7.setFont(new java.awt.Font("Microsoft Himalaya", 1, 36)); // NOI18N
        jLabel7.setText("CATEGORIA:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 170, -1));

        combocategoria.setBackground(new java.awt.Color(255, 253, 227));
        combocategoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        combocategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar categoria" }));
        jPanel1.add(combocategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 290, 40));

        jLabel5.setFont(new java.awt.Font("Microsoft Himalaya", 1, 36)); // NOI18N
        jLabel5.setText("PRECIO:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 110, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft Himalaya", 1, 36)); // NOI18N
        jLabel6.setText("$");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, 50));

        txtprecio.setBackground(new java.awt.Color(255, 253, 227));
        txtprecio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 110, 40));

        btnactualizarticket.setBackground(new java.awt.Color(238, 227, 203));
        btnactualizarticket.setFont(new java.awt.Font("MS Gothic", 1, 28)); // NOI18N
        btnactualizarticket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comprobado (1).png"))); // NOI18N
        btnactualizarticket.setText("ACTUALIZAR");
        btnactualizarticket.setBorder(null);
        jPanel1.add(btnactualizarticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 200, -1));

        btncancelarticket.setBackground(new java.awt.Color(238, 227, 203));
        btncancelarticket.setFont(new java.awt.Font("MS Gothic", 1, 28)); // NOI18N
        btncancelarticket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-x.png"))); // NOI18N
        btncancelarticket.setText("CANCELAR");
        btncancelarticket.setBorder(null);
        btncancelarticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarticketActionPerformed(evt);
            }
        });
        jPanel1.add(btncancelarticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 220, -1));

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel1.setText("categoria: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel4.setText("Cambia el valor de un precio de ticket dependiendo de su");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ticket (1) (2).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 340, 320));

        jLabel8.setFont(new java.awt.Font("MS Gothic", 1, 44)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(250, 112, 112));
        jLabel8.setText("TICKETS");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 487, 170, -1));

        jLabel9.setFont(new java.awt.Font("MS Gothic", 1, 44)); // NOI18N
        jLabel9.setText("TICKETS");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 970, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelarticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarticketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelarticketActionPerformed

    public JButton getBtnactualizarticket() {
        return btnactualizarticket;
    }

    public void setBtnactualizarticket(JButton btnactualizarticket) {
        this.btnactualizarticket = btnactualizarticket;
    }

    public JButton getBtncancelarticket() {
        return btncancelarticket;
    }

    public void setBtncancelarticket(JButton btncancelarticket) {
        this.btncancelarticket = btncancelarticket;
    }

    public JComboBox<String> getCombocategoria() {
        return combocategoria;
    }

    public void setCombocategoria(JComboBox<String> combocategoria) {
        this.combocategoria = combocategoria;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JTextField getTxtprecio() {
        return txtprecio;
    }

    public void setTxtprecio(JTextField txtprecio) {
        this.txtprecio = txtprecio;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizarticket;
    private javax.swing.JButton btncancelarticket;
    private javax.swing.JComboBox<String> combocategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
