/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.toedter.calendar.JDateChooser;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 * @author ALEJO
 */
public class viewRegistrarEmpleado extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistrarPersona
     */
    public viewRegistrarEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bggenero = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        lblfoto = new javax.swing.JLabel();
        btagregarfoto = new javax.swing.JButton();
        txttelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btfemenino = new javax.swing.JRadioButton();
        btmasculino = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        calendarFechanacimiento = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtcontra = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        txtconfirmacontra = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        comborol = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        btregistrar = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jProles = new javax.swing.JPanel();
        jPzoologo = new javax.swing.JPanel();
        comborama = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jPgerente = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jPcuidador = new javax.swing.JPanel();
        combosangre = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jPzsecretaria = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jSexperiencia = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(210, 215, 159));
        setBorder(null);
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName(""); // NOI18N
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(970, 630));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("MS Gothic", 1, 44)); // NOI18N
        jLabel3.setText("REGISTRO DE PERSONAL");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 18, -1, -1));
        getContentPane().add(lblfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 130, 140));

        btagregarfoto.setBackground(new java.awt.Color(210, 215, 159));
        btagregarfoto.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        btagregarfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/camara (1).png"))); // NOI18N
        btagregarfoto.setText("AGREGAR FOTO");
        btagregarfoto.setBorder(null);
        getContentPane().add(btagregarfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 250, -1, 28));

        txttelefono.setBackground(new java.awt.Color(255, 253, 227));
        txttelefono.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txttelefono.setToolTipText("INGRESE LA CONTRASEÑA");
        txttelefono.setBorder(null);
        getContentPane().add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 235, 180, 22));

        jLabel9.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jLabel9.setText("CORREO:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 93, -1, -1));

        txtcorreo.setBackground(new java.awt.Color(255, 253, 227));
        txtcorreo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtcorreo.setToolTipText("INGRESE LA CONTRASEÑA");
        txtcorreo.setBorder(null);
        getContentPane().add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 90, 191, 22));

        jLabel10.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jLabel10.setText("GENERO:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 141, -1, -1));

        btfemenino.setBackground(new java.awt.Color(255, 253, 227));
        bggenero.add(btfemenino);
        btfemenino.setText("FEMENINO");
        getContentPane().add(btfemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 137, -1, -1));

        btmasculino.setBackground(new java.awt.Color(255, 253, 227));
        bggenero.add(btmasculino);
        btmasculino.setText("MASCULINO");
        getContentPane().add(btmasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 137, -1, -1));

        jLabel14.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jLabel14.setText("FECHA DE NACIMIENTO:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 190, -1, -1));

        calendarFechanacimiento.setBackground(new java.awt.Color(255, 253, 227));
        getContentPane().add(calendarFechanacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 187, 140, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jLabel5.setText("CEDULA: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 93, -1, -1));

        txtcedula.setBackground(new java.awt.Color(255, 253, 227));
        txtcedula.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtcedula.setToolTipText("INGRESE LA CONTRASEÑA");
        txtcedula.setBorder(null);
        getContentPane().add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 90, 180, 22));

        jLabel6.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jLabel6.setText("NOMBRE:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 141, -1, -1));

        txtnombre.setBackground(new java.awt.Color(255, 253, 227));
        txtnombre.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtnombre.setToolTipText("INGRESE LA CONTRASEÑA");
        txtnombre.setBorder(null);
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 138, 180, 22));

        jLabel7.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jLabel7.setText("APELLIDO:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 190, -1, -1));

        txtapellido.setBackground(new java.awt.Color(255, 253, 227));
        txtapellido.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtapellido.setToolTipText("INGRESE LA CONTRASEÑA");
        txtapellido.setBorder(null);
        getContentPane().add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 187, 180, 22));

        jLabel8.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jLabel8.setText("TELEFONO:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 238, -1, -1));

        jLabel11.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jLabel11.setText("USUARIO:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, 30));

        txtusuario.setBackground(new java.awt.Color(255, 253, 227));
        txtusuario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtusuario.setToolTipText("INGRESE LA CONTRASEÑA");
        txtusuario.setBorder(null);
        getContentPane().add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 154, 22));

        jLabel12.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jLabel12.setText("CONTRASEÑA:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, 30));

        txtcontra.setBackground(new java.awt.Color(255, 253, 227));
        txtcontra.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtcontra.setBorder(null);
        getContentPane().add(txtcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 154, 22));

        jLabel13.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jLabel13.setText("CONFIRMAR:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, 30));

        txtconfirmacontra.setBackground(new java.awt.Color(255, 253, 227));
        txtconfirmacontra.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtconfirmacontra.setBorder(null);
        getContentPane().add(txtconfirmacontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 154, 22));

        jLabel4.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel4.setText("REGISTRO DE USUARIO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, 30));

        comborol.setBackground(new java.awt.Color(255, 253, 227));
        comborol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar rol" }));
        comborol.setBorder(null);
        comborol.setOpaque(true);
        getContentPane().add(comborol, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 234, 140, -1));

        jLabel15.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jLabel15.setText("ROL:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 238, -1, -1));

        btregistrar.setBackground(new java.awt.Color(210, 215, 159));
        btregistrar.setFont(new java.awt.Font("MS Gothic", 1, 28)); // NOI18N
        btregistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comprobado (1).png"))); // NOI18N
        btregistrar.setText("REGISTRAR");
        btregistrar.setBorder(null);
        getContentPane().add(btregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, -1, -1));

        btcancelar.setBackground(new java.awt.Color(210, 215, 159));
        btcancelar.setFont(new java.awt.Font("MS Gothic", 1, 28)); // NOI18N
        btcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-x.png"))); // NOI18N
        btcancelar.setText("CANCELAR");
        btcancelar.setBorder(null);
        getContentPane().add(btcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, -1, -1));

        jLabel16.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel16.setText("DATOS ACERCA DEL ROL");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, 30));

        jProles.setLayout(new java.awt.CardLayout());

        jPzoologo.setBackground(new java.awt.Color(210, 215, 159));

        comborama.setBackground(new java.awt.Color(255, 253, 227));
        comborama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar la rama", "Sistemática o taxonomía", "Zoogeografía", "Paleozoología", "Filogenia", "Parasitología", "Mastozoología", "Ictiología", "Entomología", "Melacología" }));
        comborama.setBorder(null);

        jLabel17.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jLabel17.setText("RAMA:");

        javax.swing.GroupLayout jPzoologoLayout = new javax.swing.GroupLayout(jPzoologo);
        jPzoologo.setLayout(jPzoologoLayout);
        jPzoologoLayout.setHorizontalGroup(
            jPzoologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPzoologoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comborama, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPzoologoLayout.setVerticalGroup(
            jPzoologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPzoologoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPzoologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comborama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(132, 132, 132))
        );

        jProles.add(jPzoologo, "card5");

        jPgerente.setBackground(new java.awt.Color(210, 215, 159));

        jLabel19.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jLabel19.setText("TITULO:");

        txtTitulo.setBackground(new java.awt.Color(255, 253, 227));
        txtTitulo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtTitulo.setToolTipText("INGRESE LA CONTRASEÑA");
        txtTitulo.setBorder(null);

        javax.swing.GroupLayout jPgerenteLayout = new javax.swing.GroupLayout(jPgerente);
        jPgerente.setLayout(jPgerenteLayout);
        jPgerenteLayout.setHorizontalGroup(
            jPgerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPgerenteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPgerenteLayout.setVerticalGroup(
            jPgerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPgerenteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPgerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(132, 132, 132))
        );

        jProles.add(jPgerente, "card4");

        jPcuidador.setBackground(new java.awt.Color(210, 215, 159));

        combosangre.setBackground(new java.awt.Color(255, 253, 227));
        combosangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo de sangre", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        combosangre.setBorder(null);

        jLabel21.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jLabel21.setText("TIPO DE SANGRE:");

        javax.swing.GroupLayout jPcuidadorLayout = new javax.swing.GroupLayout(jPcuidador);
        jPcuidador.setLayout(jPcuidadorLayout);
        jPcuidadorLayout.setHorizontalGroup(
            jPcuidadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPcuidadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combosangre, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPcuidadorLayout.setVerticalGroup(
            jPcuidadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPcuidadorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPcuidadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combosangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(132, 132, 132))
        );

        jProles.add(jPcuidador, "card2");

        jPzsecretaria.setBackground(new java.awt.Color(210, 215, 159));

        jLabel18.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jLabel18.setText("AÑOS DE EXPERIENCIA:");

        jSexperiencia.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSexperiencia.setBorder(null);

        javax.swing.GroupLayout jPzsecretariaLayout = new javax.swing.GroupLayout(jPzsecretaria);
        jPzsecretaria.setLayout(jPzsecretariaLayout);
        jPzsecretariaLayout.setHorizontalGroup(
            jPzsecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPzsecretariaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSexperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPzsecretariaLayout.setVerticalGroup(
            jPzsecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPzsecretariaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPzsecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jSexperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jProles.add(jPzsecretaria, "card3");

        getContentPane().add(jProles, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 350, 50));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOpaque(true);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 303, 917, 2));

        jLabel1.setFont(new java.awt.Font("MS Gothic", 1, 28)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trabajo-en-equipo (3).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 200, 210));

        jLabel2.setFont(new java.awt.Font("MS Gothic", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(37, 49, 109));
        jLabel2.setText("PERSONAL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 541, -1, -1));

        jLabel20.setFont(new java.awt.Font("MS Gothic", 1, 28)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(95, 111, 148));
        jLabel20.setText("PERSONAL");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 543, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bggenero;
    private javax.swing.JButton btagregarfoto;
    private javax.swing.JButton btcancelar;
    private javax.swing.JRadioButton btfemenino;
    private javax.swing.JRadioButton btmasculino;
    private javax.swing.JButton btregistrar;
    private com.toedter.calendar.JDateChooser calendarFechanacimiento;
    private javax.swing.JComboBox<String> comborama;
    private javax.swing.JComboBox<String> comborol;
    private javax.swing.JComboBox<String> combosangre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPcuidador;
    private javax.swing.JPanel jPgerente;
    private javax.swing.JPanel jProles;
    private javax.swing.JPanel jPzoologo;
    private javax.swing.JPanel jPzsecretaria;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSexperiencia;
    private javax.swing.JLabel lblfoto;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JPasswordField txtconfirmacontra;
    private javax.swing.JPasswordField txtcontra;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables

    public ButtonGroup getBggenero() {
        return bggenero;
    }

    public void setBggenero(ButtonGroup bggenero) {
        this.bggenero = bggenero;
    }

    public JButton getBtagregarfoto() {
        return btagregarfoto;
    }

    public void setBtagregarfoto(JButton btagregarfoto) {
        this.btagregarfoto = btagregarfoto;
    }

    public JButton getBtcancelar() {
        return btcancelar;
    }

    public void setBtcancelar(JButton btcancelar) {
        this.btcancelar = btcancelar;
    }

    public JRadioButton getBtfemenino() {
        return btfemenino;
    }

    public void setBtfemenino(JRadioButton btfemenino) {
        this.btfemenino = btfemenino;
    }

    public JRadioButton getBtmasculino() {
        return btmasculino;
    }

    public void setBtmasculino(JRadioButton btmasculino) {
        this.btmasculino = btmasculino;
    }

    public JButton getBtregistrar() {
        return btregistrar;
    }

    public void setBtregistrar(JButton btregistrar) {
        this.btregistrar = btregistrar;
    }

    public JDateChooser getCalendarFechanacimiento() {
        return calendarFechanacimiento;
    }

    public void setCalendarFechanacimiento(JDateChooser calendarFechanacimiento) {
        this.calendarFechanacimiento = calendarFechanacimiento;
    }

    public JComboBox<String> getComborama() {
        return comborama;
    }

    public void setComborama(JComboBox<String> comborama) {
        this.comborama = comborama;
    }

    public JComboBox<String> getComborol() {
        return comborol;
    }

    public void setComborol(JComboBox<String> comborol) {
        this.comborol = comborol;
    }

    public JComboBox<String> getCombosangre() {
        return combosangre;
    }

    public void setCombosangre(JComboBox<String> combosangre) {
        this.combosangre = combosangre;
    }

    public JPanel getjPanel2() {
        return jProles;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jProles = jPanel2;
    }

    public JPanel getjPcuidador() {
        return jPcuidador;
    }

    public void setjPcuidador(JPanel jPcuidador) {
        this.jPcuidador = jPcuidador;
    }

    public JPanel getjPgerente() {
        return jPgerente;
    }

    public void setjPgerente(JPanel jPgerente) {
        this.jPgerente = jPgerente;
    }

    public JPanel getjPzoologo() {
        return jPzoologo;
    }

    public void setjPzoologo(JPanel jPzoologo) {
        this.jPzoologo = jPzoologo;
    }

    public JPanel getjPzsecretaria() {
        return jPzsecretaria;
    }

    public void setjPzsecretaria(JPanel jPzsecretaria) {
        this.jPzsecretaria = jPzsecretaria;
    }

    public JSpinner getjSexperiencia() {
        return jSexperiencia;
    }

    public void setjSexperiencia(JSpinner jSexperiencia) {
        this.jSexperiencia = jSexperiencia;
    }

    public JLabel getLblfoto() {
        return lblfoto;
    }

    public void setLblfoto(JLabel lblfoto) {
        this.lblfoto = lblfoto;
    }

    public JTextField getTxtTitulo() {
        return txtTitulo;
    }

    public void setTxtTitulo(JTextField txtTitulo) {
        this.txtTitulo = txtTitulo;
    }

    public JTextField getTxtapellido() {
        return txtapellido;
    }

    public void setTxtapellido(JTextField txtapellido) {
        this.txtapellido = txtapellido;
    }

    public JTextField getTxtcedula() {
        return txtcedula;
    }

    public void setTxtcedula(JTextField txtcedula) {
        this.txtcedula = txtcedula;
    }

    public JPasswordField getTxtconfirmacontra() {
        return txtconfirmacontra;
    }

    public void setTxtconfirmacontra(JPasswordField txtconfirmacontra) {
        this.txtconfirmacontra = txtconfirmacontra;
    }

    public JPasswordField getTxtcontra() {
        return txtcontra;
    }

    public void setTxtcontra(JPasswordField txtcontra) {
        this.txtcontra = txtcontra;
    }

    public JTextField getTxtcorreo() {
        return txtcorreo;
    }

    public void setTxtcorreo(JTextField txtcorreo) {
        this.txtcorreo = txtcorreo;
    }

    public JTextField getTxtnombre() {
        return txtnombre;
    }

    public void setTxtnombre(JTextField txtnombre) {
        this.txtnombre = txtnombre;
    }

    public JTextField getTxttelefono() {
        return txttelefono;
    }

    public void setTxttelefono(JTextField txttelefono) {
        this.txttelefono = txttelefono;
    }

    public JTextField getTxtusuario() {
        return txtusuario;
    }

    public void setTxtusuario(JTextField txtusuario) {
        this.txtusuario = txtusuario;
    }

    public JPanel getjProles() {
        return jProles;
    }

    public void setjProles(JPanel jProles) {
        this.jProles = jProles;
    }

    

}
