/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JTextField;

/**
 *
 * @author Bryan
 */
public class viewVentaTicket extends javax.swing.JInternalFrame {

    /**
     * Creates new form viewVentaTicket
     */
    public viewVentaTicket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator6 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        txtDireccionCliente = new javax.swing.JTextField();
        txtTelefonoCliente = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        txtCedulaCliente = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        txtApellidoCliente = new javax.swing.JTextField();
        txtCorreoCliente = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JLabel();
        btnAgregarCliente = new javax.swing.JButton();
        txtidclienteNB = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnCancelarCompra = new javax.swing.JButton();
        btnConfirmarCompra = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtSUBTOTAL = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        txtDESCUENTO = new javax.swing.JLabel();
        txtTOTAL = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        txtPrecioAdultoMayor = new javax.swing.JLabel();
        btnMenosAdultoMayor = new javax.swing.JButton();
        txtCantidadAdultoMayor = new javax.swing.JLabel();
        btnMasAdultoMayor = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        txtTotalAdultoMayor = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        txtPrecioAdulto = new javax.swing.JLabel();
        btnMenosAdulto = new javax.swing.JButton();
        txtCantidadAdulto = new javax.swing.JLabel();
        btnMasAdulto = new javax.swing.JButton();
        jLabel63 = new javax.swing.JLabel();
        txtTotalAdulto = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        txtPrecioNiño = new javax.swing.JLabel();
        btnMenosNiño = new javax.swing.JButton();
        txtCantidadNiño = new javax.swing.JLabel();
        btnMasNiño = new javax.swing.JButton();
        jLabel74 = new javax.swing.JLabel();
        txtTotalNiño = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 227, 203));
        setBorder(null);
        setClosable(true);
        setOpaque(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(238, 227, 203));
        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel3.setBackground(new java.awt.Color(238, 227, 203));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        jLabel52.setText("Direccion:");
        jPanel3.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 124, -1, 30));

        txtDireccionCliente.setBackground(new java.awt.Color(255, 253, 227));
        txtDireccionCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDireccionCliente.setBorder(null);
        jPanel3.add(txtDireccionCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 124, 250, 22));

        txtTelefonoCliente.setBackground(new java.awt.Color(255, 253, 227));
        txtTelefonoCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTelefonoCliente.setBorder(null);
        jPanel3.add(txtTelefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 124, 190, 22));

        jLabel44.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        jLabel44.setText("Telefono:");
        jPanel3.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 124, -1, 30));

        jLabel42.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        jLabel42.setText("Nombre:");
        jPanel3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 88, -1, 20));

        jLabel41.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        jLabel41.setText("Cedula:");
        jPanel3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 47, -1, 30));

        txtCedulaCliente.setBackground(new java.awt.Color(255, 253, 227));
        txtCedulaCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCedulaCliente.setBorder(null);
        jPanel3.add(txtCedulaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 190, 22));

        txtNombreCliente.setBackground(new java.awt.Color(255, 253, 227));
        txtNombreCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombreCliente.setBorder(null);
        jPanel3.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 88, 190, 22));

        jLabel43.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        jLabel43.setText("Apellido:");
        jPanel3.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 47, -1, 40));

        txtApellidoCliente.setBackground(new java.awt.Color(255, 253, 227));
        txtApellidoCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtApellidoCliente.setBorder(null);
        jPanel3.add(txtApellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 250, 22));

        txtCorreoCliente.setBackground(new java.awt.Color(255, 253, 227));
        txtCorreoCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCorreoCliente.setBorder(null);
        jPanel3.add(txtCorreoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 88, 250, 22));

        jLabel51.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        jLabel51.setText("Correo:");
        jPanel3.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 88, -1, 30));

        jLabel45.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        jLabel45.setText("Fecha:");
        jPanel3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 10, 60, 40));

        txtfecha.setBackground(new java.awt.Color(238, 227, 203));
        txtfecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtfecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtfecha.setText("00-00-0000");
        txtfecha.setOpaque(true);
        jPanel3.add(txtfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 13, 110, 30));

        btnAgregarCliente.setBackground(new java.awt.Color(238, 227, 203));
        btnAgregarCliente.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        btnAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar-usuario (6).png"))); // NOI18N
        btnAgregarCliente.setText("Agregar Cliente");
        btnAgregarCliente.setBorder(null);
        btnAgregarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(btnAgregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 120, 130));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 87, -1, 160));
        getContentPane().add(txtidclienteNB, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 264, 0, 0));

        jPanel4.setBackground(new java.awt.Color(238, 227, 203));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancelarCompra.setBackground(new java.awt.Color(238, 227, 203));
        btnCancelarCompra.setFont(new java.awt.Font("MS Gothic", 1, 32)); // NOI18N
        btnCancelarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bolsa-de-la-compra (4) (1).png"))); // NOI18N
        btnCancelarCompra.setText("CANCELAR");
        btnCancelarCompra.setBorder(null);
        btnCancelarCompra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelarCompra.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel4.add(btnCancelarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 160, 130));

        btnConfirmarCompra.setBackground(new java.awt.Color(238, 227, 203));
        btnConfirmarCompra.setFont(new java.awt.Font("MS Gothic", 1, 32)); // NOI18N
        btnConfirmarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bolsa-de-la-compra (3) (1).png"))); // NOI18N
        btnConfirmarCompra.setText("CONFIRMAR");
        btnConfirmarCompra.setBorder(null);
        btnConfirmarCompra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConfirmarCompra.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel4.add(btnConfirmarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 200, 130));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 256, 830, -1));

        jLabel6.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(250, 112, 112));
        jLabel6.setText("VENTA DE BOLETOS");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 17, -1, 70));

        jLabel5.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        jLabel5.setText("VENTA DE BOLETOS");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Datos del Cliente");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 150, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ticket (5).png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 70, 70));

        jPanel2.setBackground(new java.awt.Color(238, 227, 203));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(238, 227, 203));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("SUBTOTAL");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("TOTAL");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("DESCUENTO");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txtSUBTOTAL.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtSUBTOTAL.setText("precio");

        jLabel130.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel130.setText("$");

        txtDESCUENTO.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDESCUENTO.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtDESCUENTO.setText("precio");

        txtTOTAL.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtTOTAL.setText("precio");

        jLabel134.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel134.setText("$");

        jLabel132.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel132.setText("%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel130)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSUBTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDESCUENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel132, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel134)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDESCUENTO)
                            .addComponent(jLabel132)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel134)
                            .addComponent(txtTOTAL)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel130)
                            .addComponent(txtSUBTOTAL))))
                .addContainerGap(12, Short.MAX_VALUE))
            .addComponent(jSeparator2)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 240, -1, 60));

        jPanel7.setBackground(new java.awt.Color(255, 253, 227));
        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel37.setText("ADULTOS MAYORES");
        jPanel7.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 10, -1, -1));

        jLabel55.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel55.setText("$");
        jPanel7.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        txtPrecioAdultoMayor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPrecioAdultoMayor.setText("precio");
        jPanel7.add(txtPrecioAdultoMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 50, -1));

        btnMenosAdultoMayor.setBackground(new java.awt.Color(255, 253, 227));
        btnMenosAdultoMayor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/quitar-del-carrito.png"))); // NOI18N
        btnMenosAdultoMayor.setBorder(null);
        jPanel7.add(btnMenosAdultoMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 10, -1, -1));

        txtCantidadAdultoMayor.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtCantidadAdultoMayor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCantidadAdultoMayor.setText("0");
        jPanel7.add(txtCantidadAdultoMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 70, 30));

        btnMasAdultoMayor.setBackground(new java.awt.Color(255, 253, 227));
        btnMasAdultoMayor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir-a-la-cesta (1).png"))); // NOI18N
        btnMasAdultoMayor.setBorder(null);
        btnMasAdultoMayor.setOpaque(true);
        jPanel7.add(btnMasAdultoMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, 30));

        jLabel58.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel58.setText("$");
        jPanel7.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        txtTotalAdultoMayor.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtTotalAdultoMayor.setText("precio");
        jPanel7.add(txtTotalAdultoMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 50, -1));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 155, 480, -1));

        jPanel9.setBackground(new java.awt.Color(255, 253, 227));
        jPanel9.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel53.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel53.setText("ADULTOS                   ");
        jPanel9.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));

        jLabel60.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel60.setText("$");
        jPanel9.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        txtPrecioAdulto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPrecioAdulto.setText("precio");
        jPanel9.add(txtPrecioAdulto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 50, -1));

        btnMenosAdulto.setBackground(new java.awt.Color(255, 253, 227));
        btnMenosAdulto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/quitar-del-carrito.png"))); // NOI18N
        btnMenosAdulto.setBorder(null);
        jPanel9.add(btnMenosAdulto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 30, 30));

        txtCantidadAdulto.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtCantidadAdulto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCantidadAdulto.setText("0");
        jPanel9.add(txtCantidadAdulto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 70, 30));

        btnMasAdulto.setBackground(new java.awt.Color(255, 253, 227));
        btnMasAdulto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir-a-la-cesta (1).png"))); // NOI18N
        btnMasAdulto.setBorder(null);
        btnMasAdulto.setOpaque(true);
        jPanel9.add(btnMasAdulto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 30, 30));

        jLabel63.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel63.setText("$");
        jPanel9.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        txtTotalAdulto.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtTotalAdulto.setText("precio");
        jPanel9.add(txtTotalAdulto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 50, -1));

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 102, 480, -1));

        jPanel11.setBackground(new java.awt.Color(255, 253, 227));
        jPanel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel70.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel70.setText("NIÑOS                         ");
        jPanel11.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 10, -1, -1));

        jLabel71.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel71.setText("$");
        jPanel11.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        txtPrecioNiño.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPrecioNiño.setText("precio");
        jPanel11.add(txtPrecioNiño, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 50, -1));

        btnMenosNiño.setBackground(new java.awt.Color(255, 253, 227));
        btnMenosNiño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/quitar-del-carrito.png"))); // NOI18N
        btnMenosNiño.setBorder(null);
        jPanel11.add(btnMenosNiño, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 30, 30));

        txtCantidadNiño.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtCantidadNiño.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCantidadNiño.setText("0");
        jPanel11.add(txtCantidadNiño, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 50, 30));

        btnMasNiño.setBackground(new java.awt.Color(255, 253, 227));
        btnMasNiño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir-a-la-cesta (1).png"))); // NOI18N
        btnMasNiño.setBorder(null);
        btnMasNiño.setOpaque(true);
        jPanel11.add(btnMasNiño, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 30, 30));

        jLabel74.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel74.setText("$");
        jPanel11.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        txtTotalNiño.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtTotalNiño.setText("precio");
        jPanel11.add(txtTotalNiño, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 50, -1));

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 49, 480, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(250, 112, 112));
        jLabel12.setText("TOTAL");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 5, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel9.setText("TOTAL");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 8, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(250, 112, 112));
        jLabel26.setText("TUS TICKETS");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 5, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel25.setText("TUS TICKETS");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 8, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 214, 480, 10));

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(250, 112, 112));
        jLabel14.setText("CANTIDAD");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 5, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel10.setText("CANTIDAD");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 8, -1, -1));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnCancelarCompra;
    private javax.swing.JButton btnConfirmarCompra;
    private javax.swing.JButton btnMasAdulto;
    private javax.swing.JButton btnMasAdultoMayor;
    private javax.swing.JButton btnMasNiño;
    private javax.swing.JButton btnMenosAdulto;
    private javax.swing.JButton btnMenosAdultoMayor;
    private javax.swing.JButton btnMenosNiño;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField txtApellidoCliente;
    private javax.swing.JLabel txtCantidadAdulto;
    private javax.swing.JLabel txtCantidadAdultoMayor;
    private javax.swing.JLabel txtCantidadNiño;
    private javax.swing.JTextField txtCedulaCliente;
    private javax.swing.JTextField txtCorreoCliente;
    private javax.swing.JLabel txtDESCUENTO;
    private javax.swing.JTextField txtDireccionCliente;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JLabel txtPrecioAdulto;
    private javax.swing.JLabel txtPrecioAdultoMayor;
    private javax.swing.JLabel txtPrecioNiño;
    private javax.swing.JLabel txtSUBTOTAL;
    private javax.swing.JLabel txtTOTAL;
    private javax.swing.JTextField txtTelefonoCliente;
    private javax.swing.JLabel txtTotalAdulto;
    private javax.swing.JLabel txtTotalAdultoMayor;
    private javax.swing.JLabel txtTotalNiño;
    private javax.swing.JLabel txtfecha;
    private javax.swing.JTextField txtidclienteNB;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAgregarCliente() {
        return btnAgregarCliente;
    }

    public void setBtnAgregarCliente(JButton btnAgregarCliente) {
        this.btnAgregarCliente = btnAgregarCliente;
    }

    public JButton getBtnCancelarCompra() {
        return btnCancelarCompra;
    }

    public void setBtnCancelarCompra(JButton btnCancelarCompra) {
        this.btnCancelarCompra = btnCancelarCompra;
    }

    public JButton getBtnConfirmarCompra() {
        return btnConfirmarCompra;
    }

    public void setBtnConfirmarCompra(JButton btnConfirmarCompra) {
        this.btnConfirmarCompra = btnConfirmarCompra;
    }

    public JButton getBtnMasAdulto() {
        return btnMasAdulto;
    }

    public void setBtnMasAdulto(JButton btnMasAdulto) {
        this.btnMasAdulto = btnMasAdulto;
    }

    public JButton getBtnMasAdultoMayor() {
        return btnMasAdultoMayor;
    }

    public void setBtnMasAdultoMayor(JButton btnMasAdultoMayor) {
        this.btnMasAdultoMayor = btnMasAdultoMayor;
    }

    public JButton getBtnMasNiño() {
        return btnMasNiño;
    }

    public void setBtnMasNiño(JButton btnMasNiño) {
        this.btnMasNiño = btnMasNiño;
    }

    public JButton getBtnMenosAdulto() {
        return btnMenosAdulto;
    }

    public void setBtnMenosAdulto(JButton btnMenosAdulto) {
        this.btnMenosAdulto = btnMenosAdulto;
    }

    public JButton getBtnMenosAdultoMayor() {
        return btnMenosAdultoMayor;
    }

    public void setBtnMenosAdultoMayor(JButton btnMenosAdultoMayor) {
        this.btnMenosAdultoMayor = btnMenosAdultoMayor;
    }

    public JButton getBtnMenosNiño() {
        return btnMenosNiño;
    }

    public void setBtnMenosNiño(JButton btnMenosNiño) {
        this.btnMenosNiño = btnMenosNiño;
    }

    public JTextField getTxtApellidoCliente() {
        return txtApellidoCliente;
    }

    public void setTxtApellidoCliente(JTextField txtApellidoCliente) {
        this.txtApellidoCliente = txtApellidoCliente;
    }

    public JLabel getTxtCantidadAdulto() {
        return txtCantidadAdulto;
    }

    public void setTxtCantidadAdulto(JLabel txtCantidadAdulto) {
        this.txtCantidadAdulto = txtCantidadAdulto;
    }

    public JLabel getTxtCantidadAdultoMayor() {
        return txtCantidadAdultoMayor;
    }

    public void setTxtCantidadAdultoMayor(JLabel txtCantidadAdultoMayor) {
        this.txtCantidadAdultoMayor = txtCantidadAdultoMayor;
    }

    public JLabel getTxtCantidadNiño() {
        return txtCantidadNiño;
    }

    public void setTxtCantidadNiño(JLabel txtCantidadNiño) {
        this.txtCantidadNiño = txtCantidadNiño;
    }

    public JTextField getTxtCedulaCliente() {
        return txtCedulaCliente;
    }

    public void setTxtCedulaCliente(JTextField txtCedulaCliente) {
        this.txtCedulaCliente = txtCedulaCliente;
    }

    public JTextField getTxtCorreoCliente() {
        return txtCorreoCliente;
    }

    public void setTxtCorreoCliente(JTextField txtCorreoCliente) {
        this.txtCorreoCliente = txtCorreoCliente;
    }

    public JLabel getTxtDESCUENTO() {
        return txtDESCUENTO;
    }

    public void setTxtDESCUENTO(JLabel txtDESCUENTO) {
        this.txtDESCUENTO = txtDESCUENTO;
    }

    public JTextField getTxtDireccionCliente() {
        return txtDireccionCliente;
    }

    public void setTxtDireccionCliente(JTextField txtDireccionCliente) {
        this.txtDireccionCliente = txtDireccionCliente;
    }

    public JTextField getTxtNombreCliente() {
        return txtNombreCliente;
    }

    public void setTxtNombreCliente(JTextField txtNombreCliente) {
        this.txtNombreCliente = txtNombreCliente;
    }

    public JLabel getTxtPrecioAdulto() {
        return txtPrecioAdulto;
    }

    public void setTxtPrecioAdulto(JLabel txtPrecioAdulto) {
        this.txtPrecioAdulto = txtPrecioAdulto;
    }

    public JLabel getTxtPrecioAdultoMayor() {
        return txtPrecioAdultoMayor;
    }

    public void setTxtPrecioAdultoMayor(JLabel txtPrecioAdultoMayor) {
        this.txtPrecioAdultoMayor = txtPrecioAdultoMayor;
    }

    public JLabel getTxtPrecioNiño() {
        return txtPrecioNiño;
    }

    public void setTxtPrecioNiño(JLabel txtPrecioNiño) {
        this.txtPrecioNiño = txtPrecioNiño;
    }

    public JLabel getTxtSUBTOTAL() {
        return txtSUBTOTAL;
    }

    public void setTxtSUBTOTAL(JLabel txtSUBTOTAL) {
        this.txtSUBTOTAL = txtSUBTOTAL;
    }

    public JLabel getTxtTOTAL() {
        return txtTOTAL;
    }

    public void setTxtTOTAL(JLabel txtTOTAL) {
        this.txtTOTAL = txtTOTAL;
    }

    public JTextField getTxtTelefonoCliente() {
        return txtTelefonoCliente;
    }

    public void setTxtTelefonoCliente(JTextField txtTelefonoCliente) {
        this.txtTelefonoCliente = txtTelefonoCliente;
    }

    public JLabel getTxtTotalAdulto() {
        return txtTotalAdulto;
    }

    public void setTxtTotalAdulto(JLabel txtTotalAdulto) {
        this.txtTotalAdulto = txtTotalAdulto;
    }

    public JLabel getTxtTotalNiño() {
        return txtTotalNiño;
    }

    public void setTxtTotalNiño(JLabel txtTotalNiño) {
        this.txtTotalNiño = txtTotalNiño;
    }

    public JLabel getTxtTotalAdultoMayor() {
        return txtTotalAdultoMayor;
    }

    public void setTxtTotalAdultoMayor(JLabel txtTotalAdultoMayor) {
        this.txtTotalAdultoMayor = txtTotalAdultoMayor;
    }

    public JLabel getTxtfecha() {
        return txtfecha;
    }

    public void setTxtfecha(JLabel txtfecha) {
        this.txtfecha = txtfecha;
    }

    public JTextField getTxtidclienteNB() {
        return txtidclienteNB;
    }

    public void setTxtidclienteNB(JTextField txtidclienteNB) {
        this.txtidclienteNB = txtidclienteNB;
    }


}
