/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToolBar;

/**
 *
 * @author Bryan
 */
public class viewRegistroHabitad extends javax.swing.JInternalFrame {

    /**
     * Creates new form viewRegistroHabitad
     */
    public viewRegistroHabitad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDlgZoologo = new javax.swing.JDialog();
        lbltitulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabladlg = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jLabel10 = new javax.swing.JLabel();
        txtbuscardlg = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnseleccionardlg = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jLabel2 = new javax.swing.JLabel();
        txtidZoologoNoborrar = new javax.swing.JTextField();
        txtidHabitadNoborrar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtOtrotipo = new javax.swing.JTextField();
        txtOtrobloque = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtnombreZol = new javax.swing.JTextField();
        txtramaZol = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jbtnSelecZoologo = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboTipoHab = new javax.swing.JComboBox<>();
        jSpiCapacidad = new javax.swing.JSpinner();
        comboUbicacion = new javax.swing.JComboBox<>();
        btcancelar = new javax.swing.JButton();
        btregistrar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        txtidZoologoNoborrar1 = new javax.swing.JTextField();
        txtidHabitadNoborrar1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtOtrotipo1 = new javax.swing.JTextField();
        txtOtrobloque1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtnombreZol1 = new javax.swing.JTextField();
        txtramaZol1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jbtnSelecZoologo1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        comboTipoHab1 = new javax.swing.JComboBox<>();
        jSpiCapacidad1 = new javax.swing.JSpinner();
        comboUbicacion1 = new javax.swing.JComboBox<>();
        btcancelar1 = new javax.swing.JButton();
        btregistrar1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jDlgZoologo.setSize(new java.awt.Dimension(545, 310));
        jDlgZoologo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltitulo.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        lbltitulo.setText("SELECCIÓN DE ZOOLOGO");
        jDlgZoologo.getContentPane().add(lbltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        tabladlg.setAutoCreateRowSorter(true);
        tabladlg.setBackground(new java.awt.Color(255, 253, 227));
        tabladlg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Rama"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabladlg);

        jDlgZoologo.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 91, 510, 170));

        jToolBar1.setBackground(new java.awt.Color(238, 227, 203));
        jToolBar1.setBorder(null);
        jToolBar1.setFloatable(false);
        jToolBar1.add(jSeparator1);

        jLabel10.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar (2).png"))); // NOI18N
        jLabel10.setText("BUSCAR:  ");
        jToolBar1.add(jLabel10);

        txtbuscardlg.setBackground(new java.awt.Color(255, 253, 227));
        jToolBar1.add(txtbuscardlg);
        jToolBar1.add(jSeparator2);

        btnseleccionardlg.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnseleccionardlg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/seleccione.png"))); // NOI18N
        btnseleccionardlg.setText("SELECCIONAR");
        btnseleccionardlg.setBorder(null);
        btnseleccionardlg.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jToolBar1.add(btnseleccionardlg);
        jToolBar1.add(jSeparator3);

        jDlgZoologo.getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 41, 510, 40));

        jLabel2.setBackground(new java.awt.Color(238, 227, 203));
        jLabel2.setOpaque(true);
        jDlgZoologo.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 270));

        setBorder(null);
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtidZoologoNoborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 0, 0));
        getContentPane().add(txtidHabitadNoborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 0, 0));

        jPanel2.setBackground(new java.awt.Color(210, 215, 159));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(61, 131, 97));
        jLabel16.setText("HABITATS");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 520, -1, -1));

        txtOtrotipo.setBackground(new java.awt.Color(255, 253, 227));
        txtOtrotipo.setBorder(null);
        jPanel2.add(txtOtrotipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 153, 150, 30));

        txtOtrobloque.setBackground(new java.awt.Color(255, 253, 227));
        txtOtrobloque.setBorder(null);
        jPanel2.add(txtOtrobloque, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 279, 150, 30));

        jPanel1.setBackground(new java.awt.Color(210, 215, 159));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("NOMBRE:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 55, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("RAMA:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        txtnombreZol.setBackground(new java.awt.Color(255, 253, 227));
        txtnombreZol.setBorder(null);
        jPanel1.add(txtnombreZol, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 260, 30));

        txtramaZol.setBackground(new java.awt.Color(255, 253, 227));
        txtramaZol.setBorder(null);
        jPanel1.add(txtramaZol, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 260, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("ZOOLOGO ACARGO:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 30));

        jbtnSelecZoologo.setBackground(new java.awt.Color(255, 253, 227));
        jbtnSelecZoologo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnSelecZoologo.setText("Seleccionar");
        jbtnSelecZoologo.setBorder(null);
        jbtnSelecZoologo.setOpaque(true);
        jPanel1.add(jbtnSelecZoologo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 6, 100, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 390, -1, 141));

        jLabel14.setFont(new java.awt.Font("MS Gothic", 1, 44)); // NOI18N
        jLabel14.setText("REGISTRO DE HABITATS");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        jLabel5.setText("DATOS DE ZOOLOGO A CARGO");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        comboTipoHab.setBackground(new java.awt.Color(255, 253, 227));
        comboTipoHab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo", "Pradera", "Bosque", "Desierto", "Montaña", "Marisma", "Sabana", "Región polar", "Altiplano", "Quebrada", "Lago", "Pantano", "Río", "Arrecife de coral", "Océano", "Playa", "Otro..." }));
        comboTipoHab.setBorder(null);
        jPanel2.add(comboTipoHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 111, 260, 30));

        jSpiCapacidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpiCapacidad.setBorder(null);
        jPanel2.add(jSpiCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 195, 260, 30));

        comboUbicacion.setBackground(new java.awt.Color(255, 253, 227));
        comboUbicacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar bloque", "A", "B", "C", "D", "E", "F", "G", "H", "I", "Otro..." }));
        comboUbicacion.setBorder(null);
        jPanel2.add(comboUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 243, 260, 30));

        btcancelar.setBackground(new java.awt.Color(210, 215, 159));
        btcancelar.setFont(new java.awt.Font("MS Gothic", 1, 28)); // NOI18N
        btcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-x.png"))); // NOI18N
        btcancelar.setText("CANCELAR");
        btcancelar.setBorder(null);
        jPanel2.add(btcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, -1, -1));

        btregistrar.setBackground(new java.awt.Color(210, 215, 159));
        btregistrar.setFont(new java.awt.Font("MS Gothic", 1, 28)); // NOI18N
        btregistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comprobado (1).png"))); // NOI18N
        btregistrar.setText("REGISTRARSE");
        btregistrar.setBorder(null);
        jPanel2.add(btregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("UBICACION(BLOQUE):");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("CAPACIDAD:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("TIPO DE HABITAD:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 30));

        jLabel19.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        jLabel19.setText("HABITATS");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 523, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/earth (2).png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 460, 410));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 603));

        jInternalFrame1.setBorder(null);
        jInternalFrame1.setClosable(true);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jInternalFrame1.getContentPane().add(txtidZoologoNoborrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 0, 0));
        jInternalFrame1.getContentPane().add(txtidHabitadNoborrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 0, 0));

        jPanel3.setBackground(new java.awt.Color(210, 215, 159));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(61, 131, 97));
        jLabel20.setText("HABITATS");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 520, -1, -1));

        txtOtrotipo1.setBackground(new java.awt.Color(255, 253, 227));
        txtOtrotipo1.setBorder(null);
        jPanel3.add(txtOtrotipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 153, 150, 30));

        txtOtrobloque1.setBackground(new java.awt.Color(255, 253, 227));
        txtOtrobloque1.setBorder(null);
        jPanel3.add(txtOtrobloque1, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 279, 150, 30));

        jPanel4.setBackground(new java.awt.Color(210, 215, 159));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setText("NOMBRE:");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 55, -1, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setText("RAMA:");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        txtnombreZol1.setBackground(new java.awt.Color(255, 253, 227));
        txtnombreZol1.setBorder(null);
        jPanel4.add(txtnombreZol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 260, 30));

        txtramaZol1.setBackground(new java.awt.Color(255, 253, 227));
        txtramaZol1.setBorder(null);
        jPanel4.add(txtramaZol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 260, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("ZOOLOGO ACARGO:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 30));

        jbtnSelecZoologo1.setBackground(new java.awt.Color(255, 253, 227));
        jbtnSelecZoologo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnSelecZoologo1.setText("Seleccionar");
        jbtnSelecZoologo1.setBorder(null);
        jbtnSelecZoologo1.setOpaque(true);
        jPanel4.add(jbtnSelecZoologo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 6, 100, 30));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 390, -1, 141));

        jLabel15.setFont(new java.awt.Font("MS Gothic", 1, 44)); // NOI18N
        jLabel15.setText("REGISTRO DE HABITATS");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel12.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        jLabel12.setText("DATOS DE ZOOLOGO A CARGO");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        comboTipoHab1.setBackground(new java.awt.Color(255, 253, 227));
        comboTipoHab1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo", "Pradera", "Bosque", "Desierto", "Montaña", "Marisma", "Sabana", "Región polar", "Altiplano", "Quebrada", "Lago", "Pantano", "Río", "Arrecife de coral", "Océano", "Playa", "Otro..." }));
        comboTipoHab1.setBorder(null);
        jPanel3.add(comboTipoHab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 111, 260, 30));

        jSpiCapacidad1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpiCapacidad1.setBorder(null);
        jPanel3.add(jSpiCapacidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 195, 260, 30));

        comboUbicacion1.setBackground(new java.awt.Color(255, 253, 227));
        comboUbicacion1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar bloque", "A", "B", "C", "D", "E", "F", "G", "H", "I", "Otro..." }));
        comboUbicacion1.setBorder(null);
        jPanel3.add(comboUbicacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 243, 260, 30));

        btcancelar1.setBackground(new java.awt.Color(210, 215, 159));
        btcancelar1.setFont(new java.awt.Font("MS Gothic", 1, 28)); // NOI18N
        btcancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-x.png"))); // NOI18N
        btcancelar1.setText("CANCELAR");
        btcancelar1.setBorder(null);
        jPanel3.add(btcancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, -1, -1));

        btregistrar1.setBackground(new java.awt.Color(210, 215, 159));
        btregistrar1.setFont(new java.awt.Font("MS Gothic", 1, 28)); // NOI18N
        btregistrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comprobado (1).png"))); // NOI18N
        btregistrar1.setText("REGISTRARSE");
        btregistrar1.setBorder(null);
        jPanel3.add(btregistrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("UBICACION(BLOQUE):");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setText("CAPACIDAD:");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel24.setText("TIPO DE HABITAD:");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 30));

        jLabel25.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        jLabel25.setText("HABITATS");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 523, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/earth (2).png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 460, 410));

        jInternalFrame1.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 603));

        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton btcancelar1;
    private javax.swing.JButton btnseleccionardlg;
    private javax.swing.JButton btregistrar;
    private javax.swing.JButton btregistrar1;
    private javax.swing.JComboBox<String> comboTipoHab;
    private javax.swing.JComboBox<String> comboTipoHab1;
    private javax.swing.JComboBox<String> comboUbicacion;
    private javax.swing.JComboBox<String> comboUbicacion1;
    private javax.swing.JDialog jDlgZoologo;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JSpinner jSpiCapacidad;
    private javax.swing.JSpinner jSpiCapacidad1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbtnSelecZoologo;
    private javax.swing.JButton jbtnSelecZoologo1;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JTable tabladlg;
    private javax.swing.JTextField txtOtrobloque;
    private javax.swing.JTextField txtOtrobloque1;
    private javax.swing.JTextField txtOtrotipo;
    private javax.swing.JTextField txtOtrotipo1;
    private javax.swing.JTextField txtbuscardlg;
    private javax.swing.JTextField txtidHabitadNoborrar;
    private javax.swing.JTextField txtidHabitadNoborrar1;
    private javax.swing.JTextField txtidZoologoNoborrar;
    private javax.swing.JTextField txtidZoologoNoborrar1;
    private javax.swing.JTextField txtnombreZol;
    private javax.swing.JTextField txtnombreZol1;
    private javax.swing.JTextField txtramaZol;
    private javax.swing.JTextField txtramaZol1;
    // End of variables declaration//GEN-END:variables

    public JButton getBtcancelar() {
        return btcancelar;
    }

    public void setBtcancelar(JButton btcancelar) {
        this.btcancelar = btcancelar;
    }

    public JButton getBtregistrar() {
        return btregistrar;
    }

    public void setBtregistrar(JButton btregistrar) {
        this.btregistrar = btregistrar;
    }

    public JComboBox<String> getComboTipoHab() {
        return comboTipoHab;
    }

    public void setComboTipoHab(JComboBox<String> comboTipoHab) {
        this.comboTipoHab = comboTipoHab;
    }

    public JComboBox<String> getComboUbicacion() {
        return comboUbicacion;
    }

    public void setComboUbicacion(JComboBox<String> comboUbicacion) {
        this.comboUbicacion = comboUbicacion;
    }

    public JLabel getjLabel14() {
        return jLabel14;
    }

    public void setjLabel14(JLabel jLabel14) {
        this.jLabel14 = jLabel14;
    }

    public JLabel getjLabel16() {
        return jLabel16;
    }

    public void setjLabel16(JLabel jLabel16) {
        this.jLabel16 = jLabel16;
    }

    public JLabel getjLabel17() {
        return jLabel17;
    }

    public void setjLabel17(JLabel jLabel17) {
        this.jLabel17 = jLabel17;
    }

    public JLabel getjLabel18() {
        return jLabel18;
    }

    public void setjLabel18(JLabel jLabel18) {
        this.jLabel18 = jLabel18;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JSpinner getjSpiCapacidad() {
        return jSpiCapacidad;
    }

    public void setjSpiCapacidad(JSpinner jSpiCapacidad) {
        this.jSpiCapacidad = jSpiCapacidad;
    }

    public JButton getJbtnSelecZoologo() {
        return jbtnSelecZoologo;
    }

    public void setJbtnSelecZoologo(JButton jbtnSelecZoologo) {
        this.jbtnSelecZoologo = jbtnSelecZoologo;
    }

    public JTextField getTxtOtrobloque() {
        return txtOtrobloque;
    }

    public void setTxtOtrobloque(JTextField txtOtrobloque) {
        this.txtOtrobloque = txtOtrobloque;
    }

    public JTextField getTxtOtrotipo() {
        return txtOtrotipo;
    }

    public void setTxtOtrotipo(JTextField txtOtrotipo) {
        this.txtOtrotipo = txtOtrotipo;
    }

    public JTextField getTxtidHabitadNoborrar() {
        return txtidHabitadNoborrar;
    }

    public void setTxtidHabitadNoborrar(JTextField txtidHabitadNoborrar) {
        this.txtidHabitadNoborrar = txtidHabitadNoborrar;
    }

    public JTextField getTxtidZoologoNoborrar() {
        return txtidZoologoNoborrar;
    }

    public void setTxtidZoologoNoborrar(JTextField txtidZoologoNoborrar) {
        this.txtidZoologoNoborrar = txtidZoologoNoborrar;
    }

    public JTextField getTxtnombreZol() {
        return txtnombreZol;
    }

    public void setTxtnombreZol(JTextField txtnombreZol) {
        this.txtnombreZol = txtnombreZol;
    }

    public JTextField getTxtramaZol() {
        return txtramaZol;
    }

    public void setTxtramaZol(JTextField txtramaZol) {
        this.txtramaZol = txtramaZol;
    }

    public JButton getBtnseleccionardlg() {
        return btnseleccionardlg;
    }

    public void setBtnseleccionardlg(JButton btnseleccionardlg) {
        this.btnseleccionardlg = btnseleccionardlg;
    }

    public JDialog getjDlgZoologo() {
        return jDlgZoologo;
    }

    public void setjDlgZoologo(JDialog jDlgZoologo) {
        this.jDlgZoologo = jDlgZoologo;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JToolBar.Separator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JToolBar.Separator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JToolBar.Separator getjSeparator2() {
        return jSeparator2;
    }

    public void setjSeparator2(JToolBar.Separator jSeparator2) {
        this.jSeparator2 = jSeparator2;
    }

    public JToolBar.Separator getjSeparator3() {
        return jSeparator3;
    }

    public void setjSeparator3(JToolBar.Separator jSeparator3) {
        this.jSeparator3 = jSeparator3;
    }

    public JToolBar getjToolBar1() {
        return jToolBar1;
    }

    public void setjToolBar1(JToolBar jToolBar1) {
        this.jToolBar1 = jToolBar1;
    }

    public JLabel getLbltitulo() {
        return lbltitulo;
    }

    public void setLbltitulo(JLabel lbltitulo) {
        this.lbltitulo = lbltitulo;
    }

    public JTable getTabladlg() {
        return tabladlg;
    }

    public void setTabladlg(JTable tabladlg) {
        this.tabladlg = tabladlg;
    }

    public JTextField getTxtbuscardlg() {
        return txtbuscardlg;
    }

    public void setTxtbuscardlg(JTextField txtbuscardlg) {
        this.txtbuscardlg = txtbuscardlg;
    }


}
