/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JToolBar;

/**
 *
 * @author ALEJO
 */
public class viewRegistroDieta extends javax.swing.JInternalFrame {

    /**
     * Creates new form viewRegistroDieta
     */
    public viewRegistroDieta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DlgAlimento = new javax.swing.JDialog();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jLabel9 = new javax.swing.JLabel();
        txtbuscardlgAlimento = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnseleccionardlgAlimento = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jPanel4 = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabladlgAlimento = new javax.swing.JTable();
        DlgAnimal = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabladlgAnimal = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jLabel10 = new javax.swing.JLabel();
        txtbuscardlgAnimal = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnseleccionardlgAnimal = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jPanel5 = new javax.swing.JPanel();
        lbltitulo1 = new javax.swing.JLabel();
        txtidDietaNB = new javax.swing.JTextField();
        txtidAlimentoNB = new javax.swing.JTextField();
        txtidAnimalNB = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        combohoradieta = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnSeleccionarAliemento = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtnombrealiemento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAdescripcionAlimento = new javax.swing.JTextArea();
        txtporcion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnagregardieta = new javax.swing.JButton();
        btncancelardieta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        btnSeleccionarAnimal = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtnombreanimal = new javax.swing.JTextField();
        txtespecie = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        DlgAlimento.setSize(new java.awt.Dimension(545, 310));
        DlgAlimento.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBackground(new java.awt.Color(238, 227, 203));
        jToolBar1.setBorder(null);
        jToolBar1.setFloatable(false);
        jToolBar1.add(jSeparator1);

        jLabel9.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar (2).png"))); // NOI18N
        jLabel9.setText("BUSCAR:  ");
        jToolBar1.add(jLabel9);

        txtbuscardlgAlimento.setBackground(new java.awt.Color(255, 253, 227));
        jToolBar1.add(txtbuscardlgAlimento);
        jToolBar1.add(jSeparator2);

        btnseleccionardlgAlimento.setBackground(new java.awt.Color(238, 227, 203));
        btnseleccionardlgAlimento.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnseleccionardlgAlimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/seleccione.png"))); // NOI18N
        btnseleccionardlgAlimento.setText("SELECCIONAR");
        btnseleccionardlgAlimento.setBorder(null);
        btnseleccionardlgAlimento.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jToolBar1.add(btnseleccionardlgAlimento);
        jToolBar1.add(jSeparator3);

        DlgAlimento.getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 520, 30));

        jPanel4.setBackground(new java.awt.Color(238, 227, 203));

        lbltitulo.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        lbltitulo.setText("SELECCIÓN DE ALIMENTO");

        tabladlgAlimento.setBackground(new java.awt.Color(255, 253, 227));
        tabladlgAlimento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Descripcion"
            }
        ));
        jScrollPane2.setViewportView(tabladlgAlimento);
        if (tabladlgAlimento.getColumnModel().getColumnCount() > 0) {
            tabladlgAlimento.getColumnModel().getColumn(2).setHeaderValue("Descripcion");
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lbltitulo)
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbltitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        DlgAlimento.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 280));

        DlgAnimal.setSize(new java.awt.Dimension(545, 310));
        DlgAnimal.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabladlgAnimal.setBackground(new java.awt.Color(255, 253, 227));
        tabladlgAnimal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Especie"
            }
        ));
        jScrollPane3.setViewportView(tabladlgAnimal);

        DlgAnimal.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 510, 162));

        jToolBar2.setBackground(new java.awt.Color(238, 227, 203));
        jToolBar2.setBorder(null);
        jToolBar2.setFloatable(false);
        jToolBar2.add(jSeparator4);

        jLabel10.setBackground(new java.awt.Color(238, 227, 203));
        jLabel10.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar (2).png"))); // NOI18N
        jLabel10.setText("BUSCAR:  ");
        jToolBar2.add(jLabel10);

        txtbuscardlgAnimal.setBackground(new java.awt.Color(255, 253, 227));
        jToolBar2.add(txtbuscardlgAnimal);
        jToolBar2.add(jSeparator5);

        btnseleccionardlgAnimal.setBackground(new java.awt.Color(238, 227, 203));
        btnseleccionardlgAnimal.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnseleccionardlgAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/seleccione.png"))); // NOI18N
        btnseleccionardlgAnimal.setText("SELECCIONAR");
        btnseleccionardlgAnimal.setBorder(null);
        btnseleccionardlgAnimal.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnseleccionardlgAnimal.setOpaque(true);
        jToolBar2.add(btnseleccionardlgAnimal);
        jToolBar2.add(jSeparator6);

        DlgAnimal.getContentPane().add(jToolBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 510, -1));

        jPanel5.setBackground(new java.awt.Color(238, 227, 203));

        lbltitulo1.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        lbltitulo1.setText("SELECCIÓN DE ANIMAL");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(lbltitulo1)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbltitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        DlgAnimal.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 280));

        setBorder(null);
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtidDietaNB, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 206, 0, 0));
        getContentPane().add(txtidAlimentoNB, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 206, 0, 0));
        getContentPane().add(txtidAnimalNB, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 206, 0, 0));

        jPanel2.setBackground(new java.awt.Color(210, 215, 159));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        jLabel3.setText("REGISTRO DE DIETA");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 26, 440, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("HORARIO");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 114, -1, -1));

        combohoradieta.setBackground(new java.awt.Color(255, 253, 227));
        combohoradieta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un horario", "\"05:00\"", "\"05:30\"", "\"06:00\"", "\"06:30\"", "\"07:00\"", "\"07:30\"", "\"08:00\"", "\"08:30\"", "\"09:00\"", "\"09:30\"", "\"10:00\"", "\"10:30\"", "\"11:00\"", "\"11:30\"", "\"12:00\"", "\"12:30\"", "\"13:00\"", "\"13:30\"", "\"14:00\"", "\"14:30\"", "\"15:00\"", "\"15:30\"", "\"16:00\"", "\"16:30\"", "\"17:00\"", "\"17:30\"", "\"18:00\"", "\"18:30\"", "\"19:00\"", "\"19:30\"", "\"20:00\"", "\"20:30\"", "\"21:00\"", "\"21:30\"", "\"22:00\"", "\"22:30\"", "\"23:00\"" }));
        combohoradieta.setBorder(null);
        jPanel2.add(combohoradieta, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 110, 227, -1));

        jPanel1.setBackground(new java.awt.Color(210, 215, 159));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("ALIMENTO");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 5, -1, -1));

        btnSeleccionarAliemento.setBackground(new java.awt.Color(255, 253, 227));
        btnSeleccionarAliemento.setText("SELECCIONAR");
        btnSeleccionarAliemento.setBorder(null);
        jPanel1.add(btnSeleccionarAliemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 94, 21));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("NOMBRE:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 34, -1, 26));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setText("DESCRIPCION:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 72, -1, -1));

        txtnombrealiemento.setBackground(new java.awt.Color(255, 253, 227));
        txtnombrealiemento.setBorder(null);
        jPanel1.add(txtnombrealiemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 34, 224, 19));

        txtAdescripcionAlimento.setBackground(new java.awt.Color(255, 253, 227));
        txtAdescripcionAlimento.setColumns(20);
        txtAdescripcionAlimento.setRows(5);
        txtAdescripcionAlimento.setBorder(null);
        jScrollPane1.setViewportView(txtAdescripcionAlimento);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 72, 224, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 390, -1));

        txtporcion.setBackground(new java.awt.Color(255, 253, 227));
        txtporcion.setBorder(null);
        jPanel2.add(txtporcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 150, 200, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("PORCIÓN");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 150, -1, 20));

        btnagregardieta.setBackground(new java.awt.Color(210, 215, 159));
        btnagregardieta.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        btnagregardieta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comprobado (1).png"))); // NOI18N
        btnagregardieta.setText("AGREGAR");
        btnagregardieta.setBorder(null);
        jPanel2.add(btnagregardieta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 200, 50));

        btncancelardieta.setBackground(new java.awt.Color(210, 215, 159));
        btncancelardieta.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        btncancelardieta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-x.png"))); // NOI18N
        btncancelardieta.setText("CANCELAR");
        btncancelardieta.setBorder(null);
        jPanel2.add(btncancelardieta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, 210, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("kg.");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 150, -1, -1));

        jPanel3.setBackground(new java.awt.Color(210, 215, 159));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setText("ANIMAL:");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 5, -1, -1));

        btnSeleccionarAnimal.setBackground(new java.awt.Color(255, 253, 227));
        btnSeleccionarAnimal.setText("SELECCIONAR");
        btnSeleccionarAnimal.setBorder(null);
        jPanel3.add(btnSeleccionarAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 0, 94, 21));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setText("NOMBRE");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 41, -1, -1));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setText("ESPECIE:");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 76, -1, 23));

        txtnombreanimal.setBackground(new java.awt.Color(255, 253, 227));
        txtnombreanimal.setBorder(null);
        jPanel3.add(txtnombreanimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 34, 218, 23));

        txtespecie.setBackground(new java.awt.Color(255, 253, 227));
        txtespecie.setBorder(null);
        jPanel3.add(txtespecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 76, 218, 23));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 382, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dieta (2) (1).png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 380, 400));

        jLabel6.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(250, 112, 112));
        jLabel6.setText("DIETA");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 527, -1, -1));

        jLabel4.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        jLabel4.setText("DIETA");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 530, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 981, 629));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog DlgAlimento;
    private javax.swing.JDialog DlgAnimal;
    private javax.swing.JButton btnSeleccionarAliemento;
    private javax.swing.JButton btnSeleccionarAnimal;
    private javax.swing.JButton btnagregardieta;
    private javax.swing.JButton btncancelardieta;
    private javax.swing.JButton btnseleccionardlgAlimento;
    private javax.swing.JButton btnseleccionardlgAnimal;
    private javax.swing.JComboBox<String> combohoradieta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JLabel lbltitulo1;
    private javax.swing.JTable tabladlgAlimento;
    private javax.swing.JTable tabladlgAnimal;
    private javax.swing.JTextArea txtAdescripcionAlimento;
    private javax.swing.JTextField txtbuscardlgAlimento;
    private javax.swing.JTextField txtbuscardlgAnimal;
    private javax.swing.JTextField txtespecie;
    private javax.swing.JTextField txtidAlimentoNB;
    private javax.swing.JTextField txtidAnimalNB;
    private javax.swing.JTextField txtidDietaNB;
    private javax.swing.JTextField txtnombrealiemento;
    private javax.swing.JTextField txtnombreanimal;
    private javax.swing.JTextField txtporcion;
    // End of variables declaration//GEN-END:variables

    public JDialog getDlgAlimento() {
        return DlgAlimento;
    }

    public void setDlgAlimento(JDialog DlgAlimento) {
        this.DlgAlimento = DlgAlimento;
    }

    public JDialog getDlgAnimal() {
        return DlgAnimal;
    }

    public void setDlgAnimal(JDialog DlgAnimal) {
        this.DlgAnimal = DlgAnimal;
    }

    public JButton getBtnSeleccionarAliemento() {
        return btnSeleccionarAliemento;
    }

    public void setBtnSeleccionarAliemento(JButton btnSeleccionarAliemento) {
        this.btnSeleccionarAliemento = btnSeleccionarAliemento;
    }

    public JButton getBtnSeleccionarAnimal() {
        return btnSeleccionarAnimal;
    }

    public void setBtnSeleccionarAnimal(JButton btnSeleccionarAnimal) {
        this.btnSeleccionarAnimal = btnSeleccionarAnimal;
    }

    public JButton getBtnagregardieta() {
        return btnagregardieta;
    }

    public void setBtnagregardieta(JButton btnagregardieta) {
        this.btnagregardieta = btnagregardieta;
    }

    public JButton getBtncancelardieta() {
        return btncancelardieta;
    }

    public void setBtncancelardieta(JButton btncancelardieta) {
        this.btncancelardieta = btncancelardieta;
    }

    public JButton getBtnseleccionardlgAlimento() {
        return btnseleccionardlgAlimento;
    }

    public void setBtnseleccionardlgAlimento(JButton btnseleccionardlgAlimento) {
        this.btnseleccionardlgAlimento = btnseleccionardlgAlimento;
    }

    public JButton getBtnseleccionardlgAnimal() {
        return btnseleccionardlgAnimal;
    }

    public void setBtnseleccionardlgAnimal(JButton btnseleccionardlgAnimal) {
        this.btnseleccionardlgAnimal = btnseleccionardlgAnimal;
    }

    public JComboBox<String> getCombohoradieta() {
        return combohoradieta;
    }

    public void setCombohoradieta(JComboBox<String> combohoradieta) {
        this.combohoradieta = combohoradieta;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel16() {
        return jLabel16;
    }

    public void setjLabel16(JLabel jLabel16) {
        this.jLabel16 = jLabel16;
    }

    public JLabel getjLabel17() {
        return jLabel17;
    }

    public void setjLabel17(JLabel jLabel17) {
        this.jLabel17 = jLabel17;
    }

    public JLabel getjLabel19() {
        return jLabel19;
    }

    public void setjLabel19(JLabel jLabel19) {
        this.jLabel19 = jLabel19;
    }

    public JLabel getjLabel20() {
        return jLabel20;
    }

    public void setjLabel20(JLabel jLabel20) {
        this.jLabel20 = jLabel20;
    }

    public JLabel getjLabel21() {
        return jLabel21;
    }

    public void setjLabel21(JLabel jLabel21) {
        this.jLabel21 = jLabel21;
    }

    public JLabel getjLabel23() {
        return jLabel23;
    }

    public void setjLabel23(JLabel jLabel23) {
        this.jLabel23 = jLabel23;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    public void setjScrollPane3(JScrollPane jScrollPane3) {
        this.jScrollPane3 = jScrollPane3;
    }

    public JToolBar.Separator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JToolBar.Separator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JToolBar.Separator getjSeparator2() {
        return jSeparator2;
    }

    public void setjSeparator2(JToolBar.Separator jSeparator2) {
        this.jSeparator2 = jSeparator2;
    }

    public JToolBar.Separator getjSeparator3() {
        return jSeparator3;
    }

    public void setjSeparator3(JToolBar.Separator jSeparator3) {
        this.jSeparator3 = jSeparator3;
    }

    public JToolBar.Separator getjSeparator4() {
        return jSeparator4;
    }

    public void setjSeparator4(JToolBar.Separator jSeparator4) {
        this.jSeparator4 = jSeparator4;
    }

    public JToolBar.Separator getjSeparator5() {
        return jSeparator5;
    }

    public void setjSeparator5(JToolBar.Separator jSeparator5) {
        this.jSeparator5 = jSeparator5;
    }

    public JToolBar.Separator getjSeparator6() {
        return jSeparator6;
    }

    public void setjSeparator6(JToolBar.Separator jSeparator6) {
        this.jSeparator6 = jSeparator6;
    }

    public JToolBar getjToolBar1() {
        return jToolBar1;
    }

    public void setjToolBar1(JToolBar jToolBar1) {
        this.jToolBar1 = jToolBar1;
    }

    public JToolBar getjToolBar2() {
        return jToolBar2;
    }

    public void setjToolBar2(JToolBar jToolBar2) {
        this.jToolBar2 = jToolBar2;
    }

    public JLabel getLbltitulo() {
        return lbltitulo;
    }

    public void setLbltitulo(JLabel lbltitulo) {
        this.lbltitulo = lbltitulo;
    }

    public JLabel getLbltitulo1() {
        return lbltitulo1;
    }

    public void setLbltitulo1(JLabel lbltitulo1) {
        this.lbltitulo1 = lbltitulo1;
    }

    public JTable getTabladlgAlimento() {
        return tabladlgAlimento;
    }

    public void setTabladlgAlimento(JTable tabladlgAlimento) {
        this.tabladlgAlimento = tabladlgAlimento;
    }

    public JTable getTabladlgAnimal() {
        return tabladlgAnimal;
    }

    public void setTabladlgAnimal(JTable tabladlgAnimal) {
        this.tabladlgAnimal = tabladlgAnimal;
    }

    public JTextArea getTxtAdescripcionAlimento() {
        return txtAdescripcionAlimento;
    }

    public void setTxtAdescripcionAlimento(JTextArea txtAdescripcionAlimento) {
        this.txtAdescripcionAlimento = txtAdescripcionAlimento;
    }

    public JTextField getTxtbuscardlgAlimento() {
        return txtbuscardlgAlimento;
    }

    public void setTxtbuscardlgAlimento(JTextField txtbuscardlgAlimento) {
        this.txtbuscardlgAlimento = txtbuscardlgAlimento;
    }

    public JTextField getTxtbuscardlgAnimal() {
        return txtbuscardlgAnimal;
    }

    public void setTxtbuscardlgAnimal(JTextField txtbuscardlgAnimal) {
        this.txtbuscardlgAnimal = txtbuscardlgAnimal;
    }

    public JTextField getTxtespecie() {
        return txtespecie;
    }

    public void setTxtespecie(JTextField txtespecie) {
        this.txtespecie = txtespecie;
    }

    public JTextField getTxtidAlimentoNB() {
        return txtidAlimentoNB;
    }

    public void setTxtidAlimentoNB(JTextField txtidAlimentoNB) {
        this.txtidAlimentoNB = txtidAlimentoNB;
    }

    public JTextField getTxtidAnimalNB() {
        return txtidAnimalNB;
    }

    public void setTxtidAnimalNB(JTextField txtidAnimalNB) {
        this.txtidAnimalNB = txtidAnimalNB;
    }

    public JTextField getTxtidDietaNB() {
        return txtidDietaNB;
    }

    public void setTxtidDietaNB(JTextField txtidDietaNB) {
        this.txtidDietaNB = txtidDietaNB;
    }

    public JTextField getTxtnombrealiemento() {
        return txtnombrealiemento;
    }

    public void setTxtnombrealiemento(JTextField txtnombrealiemento) {
        this.txtnombrealiemento = txtnombrealiemento;
    }

    public JTextField getTxtnombreanimal() {
        return txtnombreanimal;
    }

    public void setTxtnombreanimal(JTextField txtnombreanimal) {
        this.txtnombreanimal = txtnombreanimal;
    }

    public JTextField getTxtporcion() {
        return txtporcion;
    }

    public void setTxtporcion(JTextField txtporcion) {
        this.txtporcion = txtporcion;
    }


}
