/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author ALEJO
 */
public class viewVistaProveedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaUsuarios
     */
    public viewVistaProveedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblProveedor = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jbtnAgregar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jBtnModificar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jBtnElimina = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jBtnImprimir = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jBtnBuscar = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        txtBuscar = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(210, 215, 159));
        setBorder(null);
        setClosable(true);
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(37, 49, 109));
        jLabel3.setText("VISTA DE PROVEEDORES");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 24, -1, -1));

        jTblProveedor.setBackground(new java.awt.Color(255, 253, 227));
        jTblProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Ciudad", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTblProveedor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 169, 940, 430));

        jToolBar1.setBackground(new java.awt.Color(210, 215, 159));
        jToolBar1.setBorder(null);

        jbtnAgregar.setBackground(new java.awt.Color(210, 215, 159));
        jbtnAgregar.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jbtnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar-usuario (5).png"))); // NOI18N
        jbtnAgregar.setText("AGREGAR");
        jbtnAgregar.setBorder(null);
        jbtnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jbtnAgregar);
        jToolBar1.add(jSeparator1);

        jBtnModificar.setBackground(new java.awt.Color(210, 215, 159));
        jBtnModificar.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jBtnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario (6).png"))); // NOI18N
        jBtnModificar.setText("MODIFICAR");
        jBtnModificar.setBorder(null);
        jBtnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jBtnModificar);
        jToolBar1.add(jSeparator2);

        jBtnElimina.setBackground(new java.awt.Color(210, 215, 159));
        jBtnElimina.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jBtnElimina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar-usuario.png"))); // NOI18N
        jBtnElimina.setText("ELIMINAR");
        jBtnElimina.setBorder(null);
        jBtnElimina.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnElimina.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jBtnElimina);
        jToolBar1.add(jSeparator3);

        jBtnImprimir.setBackground(new java.awt.Color(210, 215, 159));
        jBtnImprimir.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jBtnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/documentos (1).png"))); // NOI18N
        jBtnImprimir.setText("IMPRIMIR REPORTE");
        jBtnImprimir.setBorder(null);
        jBtnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jBtnImprimir);
        jToolBar1.add(jSeparator4);

        jBtnBuscar.setBackground(new java.awt.Color(210, 215, 159));
        jBtnBuscar.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jBtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar (3).png"))); // NOI18N
        jBtnBuscar.setText("BUSCAR");
        jBtnBuscar.setBorder(null);
        jToolBar1.add(jBtnBuscar);
        jToolBar1.add(jSeparator7);

        txtBuscar.setBackground(new java.awt.Color(183, 211, 223));
        txtBuscar.setToolTipText("PUEDE BUSCAR MEDIANTE CEDULA, NOMBRE, APELLIDO O USUARIO");
        jToolBar1.add(txtBuscar);
        jToolBar1.add(jSeparator6);
        jToolBar1.add(jSeparator5);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 89, 940, 53));
        jToolBar1.getAccessibleContext().setAccessibleName("");

        jLabel4.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(95, 111, 148));
        jLabel4.setText("VISTA DE PROVEEDORES");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 26, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/repartidor (2) (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 70, 70));

        jLabel2.setBackground(new java.awt.Color(210, 215, 159));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBuscar;
    private javax.swing.JButton jBtnElimina;
    private javax.swing.JButton jBtnImprimir;
    private javax.swing.JButton jBtnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JTable jTblProveedor;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbtnAgregar;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

    public JButton getjBtnBuscar() {
        return jBtnBuscar;
    }

    public void setjBtnBuscar(JButton jBtnBuscar) {
        this.jBtnBuscar = jBtnBuscar;
    }

    public JButton getjBtnElimina() {
        return jBtnElimina;
    }

    public void setjBtnElimina(JButton jBtnElimina) {
        this.jBtnElimina = jBtnElimina;
    }

    public JButton getjBtnImprimir() {
        return jBtnImprimir;
    }

    public void setjBtnImprimir(JButton jBtnImprimir) {
        this.jBtnImprimir = jBtnImprimir;
    }

    public JButton getjBtnModificar() {
        return jBtnModificar;
    }

    public void setjBtnModificar(JButton jBtnModificar) {
        this.jBtnModificar = jBtnModificar;
    }

    public JTable getjTblProveedor() {
        return jTblProveedor;
    }

    public void setjTblProveedor(JTable jTblProveedor) {
        this.jTblProveedor = jTblProveedor;
    }

    public JButton getJbtnAgregar() {
        return jbtnAgregar;
    }

    public void setJbtnAgregar(JButton jbtnAgregar) {
        this.jbtnAgregar = jbtnAgregar;
    }

    public JTextField getTxtBuscar() {
        return txtBuscar;
    }

    public void setTxtBuscar(JTextField txtBuscar) {
        this.txtBuscar = txtBuscar;
    }

 
}
