/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.toedter.calendar.JDateChooser;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Bryan
 */
public class viewRegistroAnimal extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistroAnimal
     */
    public viewRegistroAnimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDlgCuidador = new javax.swing.JDialog();
        lbltitulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabladlgCuidador = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jLabel12 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        txtbuscardlgCui = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnseleccionardlgCui = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        jDlgHabitat = new javax.swing.JDialog();
        lbltitulo1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabladlgHabitat = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jLabel14 = new javax.swing.JLabel();
        txtbuscardlgHab = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnseleccionardlgHab = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jLabel2 = new javax.swing.JLabel();
        buttonGroupGenero = new javax.swing.ButtonGroup();
        txtidHabitatNoborrar = new javax.swing.JTextField();
        txtidCuidadorNoborrar = new javax.swing.JTextField();
        txtidAnimalNoborrar = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        btnSeleccionarHabitat = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtTipoHabitat = new javax.swing.JTextField();
        txtUbicacion = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        btnSeleccionarCuidador = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtNombreCuidador = new javax.swing.JTextField();
        txtTipoSangre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblFotoAnimal = new javax.swing.JLabel();
        btnExaminarFoto = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        comboEspecie = new javax.swing.JComboBox<>();
        btnhembra = new javax.swing.JRadioButton();
        btnmacho = new javax.swing.JRadioButton();
        txtnombreanimal = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        calendarNacimiento = new com.toedter.calendar.JDateChooser();
        txtOtraEspecie = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        jDlgCuidador.setBackground(new java.awt.Color(238, 227, 203));
        jDlgCuidador.setResizable(false);
        jDlgCuidador.setSize(new java.awt.Dimension(545, 310));
        jDlgCuidador.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltitulo.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        lbltitulo.setText("SELECCIÓN DE CUIDADOR");
        jDlgCuidador.getContentPane().add(lbltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 420, -1));

        tabladlgCuidador.setBackground(new java.awt.Color(238, 236, 205));
        tabladlgCuidador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Tipo de sangre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabladlgCuidador);

        jDlgCuidador.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 479, 150));

        jToolBar1.setBorder(null);
        jToolBar1.setFloatable(false);

        jSeparator1.setBackground(new java.awt.Color(238, 227, 203));
        jToolBar1.add(jSeparator1);

        jLabel12.setBackground(new java.awt.Color(238, 227, 203));
        jLabel12.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar (2).png"))); // NOI18N
        jLabel12.setText("BUSCAR:  ");
        jLabel12.setOpaque(true);
        jToolBar1.add(jLabel12);

        jSeparator7.setBackground(new java.awt.Color(238, 227, 203));
        jSeparator7.setOpaque(true);
        jToolBar1.add(jSeparator7);

        txtbuscardlgCui.setBackground(new java.awt.Color(255, 253, 227));
        txtbuscardlgCui.setBorder(null);
        jToolBar1.add(txtbuscardlgCui);

        jSeparator2.setBackground(new java.awt.Color(238, 227, 203));
        jSeparator2.setOpaque(true);
        jToolBar1.add(jSeparator2);

        btnseleccionardlgCui.setBackground(new java.awt.Color(238, 227, 203));
        btnseleccionardlgCui.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnseleccionardlgCui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/seleccione.png"))); // NOI18N
        btnseleccionardlgCui.setText("SELECCIONAR");
        btnseleccionardlgCui.setBorder(null);
        btnseleccionardlgCui.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jToolBar1.add(btnseleccionardlgCui);

        jSeparator3.setBackground(new java.awt.Color(238, 227, 203));
        jSeparator3.setOpaque(true);
        jToolBar1.add(jSeparator3);

        jDlgCuidador.getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 49, 470, -1));

        jLabel1.setBackground(new java.awt.Color(238, 227, 203));
        jLabel1.setOpaque(true);
        jDlgCuidador.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 290));

        jDlgHabitat.setBackground(new java.awt.Color(238, 227, 203));
        jDlgHabitat.setResizable(false);
        jDlgHabitat.setSize(new java.awt.Dimension(545, 310));
        jDlgHabitat.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltitulo1.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        lbltitulo1.setText("SELECCIÓN DE HABITAT");
        jDlgHabitat.getContentPane().add(lbltitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 260, -1));

        tabladlgHabitat.setBackground(new java.awt.Color(238, 236, 205));
        tabladlgHabitat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Tipo", "Ubicacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabladlgHabitat);

        jDlgHabitat.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 490, 170));

        jToolBar2.setBackground(new java.awt.Color(238, 227, 203));
        jToolBar2.setBorder(null);
        jToolBar2.setFloatable(false);
        jToolBar2.setBorderPainted(false);
        jToolBar2.add(jSeparator4);

        jLabel14.setBackground(new java.awt.Color(238, 227, 203));
        jLabel14.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar (2).png"))); // NOI18N
        jLabel14.setText("BUSCAR:  ");
        jLabel14.setOpaque(true);
        jToolBar2.add(jLabel14);

        txtbuscardlgHab.setBackground(new java.awt.Color(255, 253, 227));
        txtbuscardlgHab.setBorder(null);
        jToolBar2.add(txtbuscardlgHab);
        jToolBar2.add(jSeparator5);

        btnseleccionardlgHab.setBackground(new java.awt.Color(238, 227, 203));
        btnseleccionardlgHab.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        btnseleccionardlgHab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/seleccione.png"))); // NOI18N
        btnseleccionardlgHab.setText("SELECCIONAR");
        btnseleccionardlgHab.setBorder(null);
        btnseleccionardlgHab.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jToolBar2.add(btnseleccionardlgHab);
        jToolBar2.add(jSeparator6);

        jDlgHabitat.getContentPane().add(jToolBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 51, 490, 30));

        jLabel2.setBackground(new java.awt.Color(238, 227, 203));
        jLabel2.setOpaque(true);
        jDlgHabitat.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 270));

        setBorder(null);
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(970, 630));

        jPanel1.setBackground(new java.awt.Color(210, 215, 159));
        jPanel1.setPreferredSize(new java.awt.Dimension(970, 630));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("MS Gothic", 1, 40)); // NOI18N
        jLabel3.setText("DATOS CUIDADOR/HABITAT");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, 60));

        btnCancelar.setBackground(new java.awt.Color(210, 215, 159));
        btnCancelar.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-x.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(null);
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 510, -1, 40));

        btnAgregar.setBackground(new java.awt.Color(210, 215, 159));
        btnAgregar.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comprobado (1).png"))); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.setBorder(null);
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 510, -1, 40));

        jPanel2.setBackground(new java.awt.Color(210, 215, 159));

        jLabel20.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel20.setText("HABITAT");

        btnSeleccionarHabitat.setBackground(new java.awt.Color(255, 253, 227));
        btnSeleccionarHabitat.setText("SELECCIONAR");
        btnSeleccionarHabitat.setOpaque(true);

        jLabel21.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel21.setText("TIPO:");

        jLabel22.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel22.setText("UBICACION:");

        txtTipoHabitat.setBackground(new java.awt.Color(255, 253, 227));

        txtUbicacion.setBackground(new java.awt.Color(255, 253, 227));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSeleccionarHabitat))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTipoHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(btnSeleccionarHabitat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 360, -1, 120));

        jPanel3.setBackground(new java.awt.Color(210, 215, 159));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel24.setText("CUIDADOR");
        jLabel24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, 20));

        btnSeleccionarCuidador.setBackground(new java.awt.Color(255, 253, 227));
        btnSeleccionarCuidador.setText("SELECCIONAR");
        btnSeleccionarCuidador.setOpaque(true);
        jPanel3.add(btnSeleccionarCuidador, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 0, -1, -1));

        jLabel25.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel25.setText("NOMBRE:");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 43, -1, -1));

        jLabel27.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel27.setText("TIPO DE SANGRE:");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 80, -1, -1));

        txtNombreCuidador.setBackground(new java.awt.Color(255, 253, 227));
        jPanel3.add(txtNombreCuidador, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 40, 112, -1));

        txtTipoSangre.setBackground(new java.awt.Color(255, 253, 227));
        jPanel3.add(txtTipoSangre, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 77, 66, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 367, -1, 109));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tortuga (2) (1).png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 332, -1, 190));

        jLabel10.setBackground(new java.awt.Color(255, 149, 81));
        jLabel10.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 149, 81));
        jLabel10.setText("ANIMALES");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 537, 160, -1));

        jLabel11.setFont(new java.awt.Font("MS Gothic", 1, 44)); // NOI18N
        jLabel11.setText("REGISTRO DE ANIMALES");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 35, -1, -1));

        jPanel4.setBackground(new java.awt.Color(210, 215, 159));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFotoAnimal.setBackground(new java.awt.Color(238, 227, 203));
        lblFotoAnimal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblFotoAnimal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblFotoAnimal.setOpaque(true);
        jPanel4.add(lblFotoAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 130, 140));

        btnExaminarFoto.setBackground(new java.awt.Color(255, 253, 227));
        btnExaminarFoto.setFont(new java.awt.Font("MS Gothic", 1, 16)); // NOI18N
        btnExaminarFoto.setText("EXAMINAR");
        jPanel4.add(btnExaminarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 160, 100, 30));

        jLabel6.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel6.setText("NOMBRE:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel13.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel13.setText("GENERO:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel15.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel15.setText("ESPECIE:");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 70, -1));

        comboEspecie.setBackground(new java.awt.Color(255, 253, 227));
        comboEspecie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la especie", "Mamíferos", "Aves", "Reptiles", "Ranas y sapos", "Peces", "Ciempiés y milpiés", "Arañas y alacranes", "Insectos", "Cangrejos y camarones", "Estrellas y erizos", "Caracoles, almejas y pulpos", "Lombrices y gusanos marinos", "Rotíferos", "Gusanos planos", "Medusas y corales", "Esponjas", "Otro..." }));
        jPanel4.add(comboEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 143, -1));

        buttonGroupGenero.add(btnhembra);
        btnhembra.setText("HEMBRA");
        jPanel4.add(btnhembra, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        buttonGroupGenero.add(btnmacho);
        btnmacho.setText("MACHO");
        jPanel4.add(btnmacho, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        txtnombreanimal.setBackground(new java.awt.Color(255, 253, 227));
        jPanel4.add(txtnombreanimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 147, -1));

        jLabel17.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel17.setText("FECHA DE NACIMIENTO:");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        calendarNacimiento.setBackground(new java.awt.Color(255, 253, 227));
        jPanel4.add(calendarNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 130, -1));

        txtOtraEspecie.setBackground(new java.awt.Color(255, 253, 227));
        jPanel4.add(txtOtraEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 114, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 98, -1, -1));

        jLabel16.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 192, 144));
        jLabel16.setText("ANIMALES");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 540, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(447, 447, 447)
                    .addComponent(txtidHabitatNoborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(70, 70, 70)
                    .addComponent(txtidCuidadorNoborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtidAnimalNoborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(447, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(315, 315, 315)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtidHabitatNoborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtidCuidadorNoborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtidAnimalNoborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(291, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExaminarFoto;
    private javax.swing.JButton btnSeleccionarCuidador;
    private javax.swing.JButton btnSeleccionarHabitat;
    private javax.swing.JRadioButton btnhembra;
    private javax.swing.JRadioButton btnmacho;
    private javax.swing.JButton btnseleccionardlgCui;
    private javax.swing.JButton btnseleccionardlgHab;
    private javax.swing.ButtonGroup buttonGroupGenero;
    private com.toedter.calendar.JDateChooser calendarNacimiento;
    private javax.swing.JComboBox<String> comboEspecie;
    private javax.swing.JDialog jDlgCuidador;
    private javax.swing.JDialog jDlgHabitat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel lblFotoAnimal;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JLabel lbltitulo1;
    private javax.swing.JTable tabladlgCuidador;
    private javax.swing.JTable tabladlgHabitat;
    private javax.swing.JTextField txtNombreCuidador;
    private javax.swing.JTextField txtOtraEspecie;
    private javax.swing.JTextField txtTipoHabitat;
    private javax.swing.JTextField txtTipoSangre;
    private javax.swing.JTextField txtUbicacion;
    private javax.swing.JTextField txtbuscardlgCui;
    private javax.swing.JTextField txtbuscardlgHab;
    private javax.swing.JTextField txtidAnimalNoborrar;
    private javax.swing.JTextField txtidCuidadorNoborrar;
    private javax.swing.JTextField txtidHabitatNoborrar;
    private javax.swing.JTextField txtnombreanimal;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAgregar() {
        return btnAgregar;
    }

    public void setBtnAgregar(JButton btnAgregar) {
        this.btnAgregar = btnAgregar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JButton getBtnExaminarFoto() {
        return btnExaminarFoto;
    }

    public void setBtnExaminarFoto(JButton btnExaminarFoto) {
        this.btnExaminarFoto = btnExaminarFoto;
    }

    public JButton getBtnSeleccionarCuidador() {
        return btnSeleccionarCuidador;
    }

    public void setBtnSeleccionarCuidador(JButton btnSeleccionarCuidador) {
        this.btnSeleccionarCuidador = btnSeleccionarCuidador;
    }

    public JButton getBtnSeleccionarHabitat() {
        return btnSeleccionarHabitat;
    }

    public void setBtnSeleccionarHabitat(JButton btnSeleccionarHabitat) {
        this.btnSeleccionarHabitat = btnSeleccionarHabitat;
    }

    public JRadioButton getBtnhembra() {
        return btnhembra;
    }

    public void setBtnhembra(JRadioButton btnhembra) {
        this.btnhembra = btnhembra;
    }

    public JRadioButton getBtnmacho() {
        return btnmacho;
    }

    public void setBtnmacho(JRadioButton btnmacho) {
        this.btnmacho = btnmacho;
    }

    public JButton getBtnseleccionardlgCui() {
        return btnseleccionardlgCui;
    }

    public void setBtnseleccionardlgCui(JButton btnseleccionardlgCui) {
        this.btnseleccionardlgCui = btnseleccionardlgCui;
    }

    public JButton getBtnseleccionardlgHab() {
        return btnseleccionardlgHab;
    }

    public void setBtnseleccionardlgHab(JButton btnseleccionardlgHab) {
        this.btnseleccionardlgHab = btnseleccionardlgHab;
    }

    public ButtonGroup getButtonGroupGenero() {
        return buttonGroupGenero;
    }

    public void setButtonGroupGenero(ButtonGroup buttonGroupGenero) {
        this.buttonGroupGenero = buttonGroupGenero;
    }

    public JDateChooser getCalendarNacimiento() {
        return calendarNacimiento;
    }

    public void setCalendarNacimiento(JDateChooser calendarNacimiento) {
        this.calendarNacimiento = calendarNacimiento;
    }

    public JComboBox<String> getComboEspecie() {
        return comboEspecie;
    }

    public void setComboEspecie(JComboBox<String> comboEspecie) {
        this.comboEspecie = comboEspecie;
    }

    public JDialog getjDlgCuidador() {
        return jDlgCuidador;
    }

    public void setjDlgCuidador(JDialog jDlgCuidador) {
        this.jDlgCuidador = jDlgCuidador;
    }

    public JDialog getjDlgHabitat() {
        return jDlgHabitat;
    }

    public void setjDlgHabitat(JDialog jDlgHabitat) {
        this.jDlgHabitat = jDlgHabitat;
    }

    public JLabel getLblFotoAnimal() {
        return lblFotoAnimal;
    }

    public void setLblFotoAnimal(JLabel lblFotoAnimal) {
        this.lblFotoAnimal = lblFotoAnimal;
    }

    public JLabel getLbltitulo() {
        return lbltitulo;
    }

    public void setLbltitulo(JLabel lbltitulo) {
        this.lbltitulo = lbltitulo;
    }

    public JLabel getLbltitulo1() {
        return lbltitulo1;
    }

    public void setLbltitulo1(JLabel lbltitulo1) {
        this.lbltitulo1 = lbltitulo1;
    }

    public JTable getTabladlgCuidador() {
        return tabladlgCuidador;
    }

    public void setTabladlgCuidador(JTable tabladlgCuidador) {
        this.tabladlgCuidador = tabladlgCuidador;
    }

    public JTable getTabladlgHabitat() {
        return tabladlgHabitat;
    }

    public void setTabladlgHabitat(JTable tabladlgHabitat) {
        this.tabladlgHabitat = tabladlgHabitat;
    }

    public JTextField getTxtUbicacion() {
        return txtUbicacion;
    }

    public void setTxtUbicacion(JTextField txtUbicacion) {
        this.txtUbicacion = txtUbicacion;
    }

    public JTextField getTxtNombreCuidador() {
        return txtNombreCuidador;
    }

    public JTextField getTxtOtraEspecie() {
        return txtOtraEspecie;
    }

    public void setTxtOtraEspecie(JTextField txtOtraEspecie) {
        this.txtOtraEspecie = txtOtraEspecie;
    }

    public void setTxtNombreCuidador(JTextField txtNombreCuidador) {
        this.txtNombreCuidador = txtNombreCuidador;
    }

    public JTextField getTxtTipoHabitat() {
        return txtTipoHabitat;
    }

    public void setTxtTipoHabitat(JTextField txtTipoHabitat) {
        this.txtTipoHabitat = txtTipoHabitat;
    }

    public JTextField getTxtTipoSangre() {
        return txtTipoSangre;
    }

    public void setTxtTipoSangre(JTextField txtTipoSangre) {
        this.txtTipoSangre = txtTipoSangre;
    }

    public JTextField getTxtbuscardlgCui() {
        return txtbuscardlgCui;
    }

    public void setTxtbuscardlgCui(JTextField txtbuscardlgCui) {
        this.txtbuscardlgCui = txtbuscardlgCui;
    }

    public JTextField getTxtbuscardlgHab() {
        return txtbuscardlgHab;
    }

    public void setTxtbuscardlgHab(JTextField txtbuscardlgHab) {
        this.txtbuscardlgHab = txtbuscardlgHab;
    }

    public JTextField getTxtidAnimalNoborrar() {
        return txtidAnimalNoborrar;
    }

    public void setTxtidAnimalNoborrar(JTextField txtidAnimalNoborrar) {
        this.txtidAnimalNoborrar = txtidAnimalNoborrar;
    }

    public JTextField getTxtidCuidadorNoborrar() {
        return txtidCuidadorNoborrar;
    }

    public void setTxtidCuidadorNoborrar(JTextField txtidCuidadorNoborrar) {
        this.txtidCuidadorNoborrar = txtidCuidadorNoborrar;
    }

    public JTextField getTxtidHabitatNoborrar() {
        return txtidHabitatNoborrar;
    }

    public void setTxtidHabitatNoborrar(JTextField txtidHabitatNoborrar) {
        this.txtidHabitatNoborrar = txtidHabitatNoborrar;
    }

    public JTextField getTxtnombreanimal() {
        return txtnombreanimal;
    }

    public void setTxtnombreanimal(JTextField txtnombreanimal) {
        this.txtnombreanimal = txtnombreanimal;
    }

}
