/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToolBar;

/**
 *
 * @author Bryan
 */
public class viewVistaCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form viewVistaCliente
     */
    public viewVistaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblCliente = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnAgregarCliente = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        BtnModificarCliente = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnEliminarCliente = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jBtnImprimirCliente = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        txtbuscar = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jBtnBuscarCliente = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setBackground(new java.awt.Color(210, 215, 159));
        setBorder(null);
        setClosable(true);
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(970, 654));
        setRequestFocusEnabled(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(250, 112, 112));
        jLabel4.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(61, 131, 97));
        jLabel4.setText("VISTA DE CLIENTES");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 450, 50));

        jLabel3.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        jLabel3.setText("VISTA DE CLIENTES");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 9, 440, 80));

        jTblCliente.setBackground(new java.awt.Color(255, 253, 227));
        jTblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Cedula", "Nombre", "Apellido", "Correo", "Direccion", "Telefono", "Fecha de Registro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTblCliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 178, 940, 420));

        jToolBar1.setBackground(new java.awt.Color(210, 215, 159));
        jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToolBar1.setBorderPainted(false);
        jToolBar1.add(jSeparator1);

        btnAgregarCliente.setBackground(new java.awt.Color(210, 215, 159));
        btnAgregarCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/invitacion.png"))); // NOI18N
        btnAgregarCliente.setText("AGREGAR");
        btnAgregarCliente.setBorder(null);
        btnAgregarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAgregarCliente);
        jToolBar1.add(jSeparator5);

        BtnModificarCliente.setBackground(new java.awt.Color(210, 215, 159));
        BtnModificarCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnModificarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario (7).png"))); // NOI18N
        BtnModificarCliente.setText("MODIFICAR");
        BtnModificarCliente.setBorder(null);
        BtnModificarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnModificarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(BtnModificarCliente);
        jToolBar1.add(jSeparator2);

        btnEliminarCliente.setBackground(new java.awt.Color(210, 215, 159));
        btnEliminarCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar-usuario (1).png"))); // NOI18N
        btnEliminarCliente.setText("ELIMINAR");
        btnEliminarCliente.setBorder(null);
        btnEliminarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnEliminarCliente);
        jToolBar1.add(jSeparator3);

        jBtnImprimirCliente.setBackground(new java.awt.Color(210, 215, 159));
        jBtnImprimirCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnImprimirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/documentos.png"))); // NOI18N
        jBtnImprimirCliente.setText("IMPRIMIR REPORTE");
        jBtnImprimirCliente.setBorder(null);
        jBtnImprimirCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnImprimirCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jBtnImprimirCliente);
        jToolBar1.add(jSeparator4);

        txtbuscar.setBackground(new java.awt.Color(177, 215, 180));
        txtbuscar.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        txtbuscar.setToolTipText("PUEDE BUSCAR MEDIANTE CEDULA, NOMBRE, APELLIDO O USUARIO");
        txtbuscar.setBorder(null);
        txtbuscar.setPreferredSize(new java.awt.Dimension(50, 22));
        jToolBar1.add(txtbuscar);
        jToolBar1.add(jSeparator6);

        jBtnBuscarCliente.setBackground(new java.awt.Color(210, 215, 159));
        jBtnBuscarCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar (3).png"))); // NOI18N
        jBtnBuscarCliente.setText("BUSCAR");
        jBtnBuscarCliente.setBorder(null);
        jBtnBuscarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnBuscarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jBtnBuscarCliente);
        jToolBar1.add(jSeparator8);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 100, 940, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cliente (2) (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 70, 70));

        jLabel2.setBackground(new java.awt.Color(210, 215, 159));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnModificarCliente;
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton jBtnBuscarCliente;
    private javax.swing.JButton jBtnImprimirCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JTable jTblCliente;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnModificarCliente() {
        return BtnModificarCliente;
    }

    public void setBtnModificarCliente(JButton BtnModificarCliente) {
        this.BtnModificarCliente = BtnModificarCliente;
    }

    public JButton getBtnAgregarCliente() {
        return btnAgregarCliente;
    }

    public void setBtnAgregarCliente(JButton btnAgregarCliente) {
        this.btnAgregarCliente = btnAgregarCliente;
    }

    public JButton getBtnEliminarCliente() {
        return btnEliminarCliente;
    }

    public void setBtnEliminarCliente(JButton btnEliminarCliente) {
        this.btnEliminarCliente = btnEliminarCliente;
    }

    public JButton getjBtnBuscarCliente() {
        return jBtnBuscarCliente;
    }

    public void setjBtnBuscarCliente(JButton jBtnBuscarCliente) {
        this.jBtnBuscarCliente = jBtnBuscarCliente;
    }

    public JButton getjBtnImprimirCliente() {
        return jBtnImprimirCliente;
    }

    public void setjBtnImprimirCliente(JButton jBtnImprimirCliente) {
        this.jBtnImprimirCliente = jBtnImprimirCliente;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JToolBar.Separator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JToolBar.Separator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JToolBar.Separator getjSeparator2() {
        return jSeparator2;
    }

    public void setjSeparator2(JToolBar.Separator jSeparator2) {
        this.jSeparator2 = jSeparator2;
    }

    public JToolBar.Separator getjSeparator3() {
        return jSeparator3;
    }

    public void setjSeparator3(JToolBar.Separator jSeparator3) {
        this.jSeparator3 = jSeparator3;
    }

    public JToolBar.Separator getjSeparator4() {
        return jSeparator4;
    }

    public void setjSeparator4(JToolBar.Separator jSeparator4) {
        this.jSeparator4 = jSeparator4;
    }

    public JTable getjTblCliente() {
        return jTblCliente;
    }

    public void setjTblCliente(JTable jTblCliente) {
        this.jTblCliente = jTblCliente;
    }

    public JTextField getjTextField1() {
        return txtbuscar;
    }

    public void setjTextField1(JTextField jTextField1) {
        this.txtbuscar = jTextField1;
    }

    public JToolBar getjToolBar1() {
        return jToolBar1;
    }

    public void setjToolBar1(JToolBar jToolBar1) {
        this.jToolBar1 = jToolBar1;
    }

    public JTextField getTxtbuscar() {
        return txtbuscar;
    }

    public void setTxtbuscar(JTextField txtbuscar) {
        this.txtbuscar = txtbuscar;
    }

}
