/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToolBar;

/**
 *
 * @author Bryan
 */
public class viewVistaAnimal extends javax.swing.JInternalFrame {

    /**
     * Creates new form viewVistaAnimal
     */
    public viewVistaAnimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblAnimal = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jbtnAgregarAnimal = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jBtnModificarAnimal = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jBtnEliminarAnimal = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jBtnImprimirAnimal = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jBtnBuscarAnimal = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        txtbuscarAnimal = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(210, 215, 159));
        setBorder(null);
        setClosable(true);
        setPreferredSize(new java.awt.Dimension(970, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(250, 112, 112));
        jLabel4.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 149, 81));
        jLabel4.setText("VISTA DE ANIMALES");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 25, -1, -1));

        jLabel3.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 192, 144));
        jLabel3.setText("VISTA DE ANIMALES");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 27, -1, -1));

        jTblAnimal.setBackground(new java.awt.Color(255, 253, 227));
        jTblAnimal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Genero", "Especie", "Fecha de Naciemiento", "Habitad", "Cuidador", "Foto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblAnimal.setGridColor(new java.awt.Color(255, 253, 227));
        jTblAnimal.setShowGrid(true);
        jScrollPane1.setViewportView(jTblAnimal);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 167, 940, 433));

        jToolBar1.setBackground(new java.awt.Color(210, 215, 159));
        jToolBar1.setBorder(null);
        jToolBar1.add(jSeparator7);

        jbtnAgregarAnimal.setBackground(new java.awt.Color(210, 215, 159));
        jbtnAgregarAnimal.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jbtnAgregarAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/leon (6).png"))); // NOI18N
        jbtnAgregarAnimal.setText("AGREGAR");
        jbtnAgregarAnimal.setBorder(null);
        jbtnAgregarAnimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnAgregarAnimal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jbtnAgregarAnimal);
        jToolBar1.add(jSeparator1);

        jBtnModificarAnimal.setBackground(new java.awt.Color(210, 215, 159));
        jBtnModificarAnimal.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jBtnModificarAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar (7).png"))); // NOI18N
        jBtnModificarAnimal.setText("MODIFICAR");
        jBtnModificarAnimal.setBorder(null);
        jBtnModificarAnimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnModificarAnimal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jBtnModificarAnimal);
        jToolBar1.add(jSeparator2);

        jBtnEliminarAnimal.setBackground(new java.awt.Color(210, 215, 159));
        jBtnEliminarAnimal.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jBtnEliminarAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        jBtnEliminarAnimal.setText("ELIMINAR");
        jBtnEliminarAnimal.setBorder(null);
        jBtnEliminarAnimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnEliminarAnimal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jBtnEliminarAnimal);
        jToolBar1.add(jSeparator3);

        jBtnImprimirAnimal.setBackground(new java.awt.Color(210, 215, 159));
        jBtnImprimirAnimal.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jBtnImprimirAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/documentos (2).png"))); // NOI18N
        jBtnImprimirAnimal.setText("IMPRIMIR REPORTE");
        jBtnImprimirAnimal.setBorder(null);
        jBtnImprimirAnimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnImprimirAnimal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jBtnImprimirAnimal);
        jToolBar1.add(jSeparator4);

        jBtnBuscarAnimal.setBackground(new java.awt.Color(210, 215, 159));
        jBtnBuscarAnimal.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jBtnBuscarAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar (4).png"))); // NOI18N
        jBtnBuscarAnimal.setText("BUSCAR");
        jBtnBuscarAnimal.setBorder(null);
        jToolBar1.add(jBtnBuscarAnimal);
        jToolBar1.add(jSeparator8);

        txtbuscarAnimal.setBackground(new java.awt.Color(255, 253, 227));
        txtbuscarAnimal.setToolTipText("PUEDE BUSCAR MEDIANTE CEDULA, NOMBRE, APELLIDO O USUARIO");
        jToolBar1.add(txtbuscarAnimal);
        jToolBar1.add(jSeparator6);
        jToolBar1.add(jSeparator5);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 96, 940, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/leon (5) (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 70, 70));

        jLabel2.setBackground(new java.awt.Color(210, 215, 159));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBuscarAnimal;
    private javax.swing.JButton jBtnEliminarAnimal;
    private javax.swing.JButton jBtnImprimirAnimal;
    private javax.swing.JButton jBtnModificarAnimal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JTable jTblAnimal;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbtnAgregarAnimal;
    private javax.swing.JTextField txtbuscarAnimal;
    // End of variables declaration//GEN-END:variables

    public JButton getjBtnBuscarAnimal() {
        return jBtnBuscarAnimal;
    }

    public void setjBtnBuscarAnimal(JButton jBtnBuscarAnimal) {
        this.jBtnBuscarAnimal = jBtnBuscarAnimal;
    }

    public JButton getjBtnEliminarAnimal() {
        return jBtnEliminarAnimal;
    }

    public void setjBtnEliminarAnimal(JButton jBtnEliminarAnimal) {
        this.jBtnEliminarAnimal = jBtnEliminarAnimal;
    }

    public JButton getjBtnImprimirAnimal() {
        return jBtnImprimirAnimal;
    }

    public void setjBtnImprimirAnimal(JButton jBtnImprimirAnimal) {
        this.jBtnImprimirAnimal = jBtnImprimirAnimal;
    }

    public JButton getjBtnModificarAnimal() {
        return jBtnModificarAnimal;
    }

    public void setjBtnModificarAnimal(JButton jBtnModificarAnimal) {
        this.jBtnModificarAnimal = jBtnModificarAnimal;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JToolBar.Separator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JToolBar.Separator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JToolBar.Separator getjSeparator2() {
        return jSeparator2;
    }

    public void setjSeparator2(JToolBar.Separator jSeparator2) {
        this.jSeparator2 = jSeparator2;
    }

    public JToolBar.Separator getjSeparator3() {
        return jSeparator3;
    }

    public void setjSeparator3(JToolBar.Separator jSeparator3) {
        this.jSeparator3 = jSeparator3;
    }

    public JToolBar.Separator getjSeparator4() {
        return jSeparator4;
    }

    public void setjSeparator4(JToolBar.Separator jSeparator4) {
        this.jSeparator4 = jSeparator4;
    }

    public JTable getjTblAnimal() {
        return jTblAnimal;
    }

    public void setjTblAnimal(JTable jTblAnimal) {
        this.jTblAnimal = jTblAnimal;
    }

    public JToolBar getjToolBar1() {
        return jToolBar1;
    }

    public void setjToolBar1(JToolBar jToolBar1) {
        this.jToolBar1 = jToolBar1;
    }

    public JButton getJbtnAgregarAnimal() {
        return jbtnAgregarAnimal;
    }

    public void setJbtnAgregarAnimal(JButton jbtnAgregarAnimal) {
        this.jbtnAgregarAnimal = jbtnAgregarAnimal;
    }

    public JTextField getTxtbuscarAnimal() {
        return txtbuscarAnimal;
    }

    public void setTxtbuscarAnimal(JTextField txtbuscarAnimal) {
        this.txtbuscarAnimal = txtbuscarAnimal;
    }




}
